(()=>{'use strict';
function setup(m){
  const canvas=m.querySelector('.nm-canvas'),paint=canvas.getContext('2d'),button=m.querySelector('.noise-start'),status=m.querySelector('.nm-status'),value=m.querySelector('.nm-value'),range=m.querySelector('.noise-range'),sensitivity=m.querySelector('.noise-sensitivity'),view=m.querySelector('.noise-view-select');
  let stream=null,context=null,analyser=null,frame=0,active=false,pending=false,disposed=false,generation=0,level=0,peak=0,width=300,height=180,lastLabel=0;const samples=new Uint8Array(1024),history=Array(64).fill(0);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function draw(){
    paint.clearRect(0,0,width,height);const color=level>=Number(range.value)?'#dc8b75':getComputedStyle(m).getPropertyValue('--meter-color').trim()||'#72aaa4',quiet=getComputedStyle(m).getPropertyValue('--module-text').trim()||'#23343b';
    if(view.value==='single'){
      const inset=Math.min(12,width*.06),bar=Math.max(1,width-inset*2),x=inset,h=Math.max(1,height-8),y=4,radius=Math.min(24,bar/2,h/2);paint.fillStyle=quiet;paint.globalAlpha=.08;paint.beginPath();paint.roundRect(x,y,bar,h,radius);paint.fill();paint.globalAlpha=1;paint.save();paint.beginPath();paint.roundRect(x,y,bar,h,radius);paint.clip();const gradient=paint.createLinearGradient(0,y+h,0,y);gradient.addColorStop(0,color);gradient.addColorStop(1,color+'99');paint.fillStyle=gradient;paint.fillRect(x,y+h*(1-level/100),bar,h*level/100);paint.restore();const marker=y+h*(1-Number(range.value)/100);paint.strokeStyle=color;paint.setLineDash([4,3]);paint.beginPath();paint.moveTo(0,marker);paint.lineTo(width,marker);paint.stroke();paint.setLineDash([]);
    }else if(view.value==='waveform'){
      paint.beginPath();history.forEach((v,i)=>{const x=i/(history.length-1)*width,y=height*.76-v/100*height*.6;i?paint.lineTo(x,y):paint.moveTo(x,y)});paint.lineTo(width,height);paint.lineTo(0,height);paint.closePath();const fill=paint.createLinearGradient(0,0,0,height);fill.addColorStop(0,color+'77');fill.addColorStop(1,color+'00');paint.fillStyle=fill;paint.fill();paint.beginPath();history.forEach((v,i)=>{const x=i/(history.length-1)*width,y=height*.76-v/100*height*.6;i?paint.lineTo(x,y):paint.moveTo(x,y)});paint.strokeStyle=color;paint.lineWidth=3;paint.lineJoin='round';paint.stroke();
    }else{

      const vertical=view.value==='vertical',count=vertical?32:28,gap=Math.min(4,width/(count*3)),barWidth=(width-gap*(count-1))/count;
      const h=vertical?height*.8:Math.min(70,height*.45),top=vertical?height*.1:height*.27;
      for(let i=0;i<count;i++){const x=i*(barWidth+gap);paint.globalAlpha=.08;paint.fillStyle=quiet;paint.beginPath();paint.roundRect(x,top,barWidth,h,Math.min(3,barWidth/2));paint.fill();paint.globalAlpha=1;paint.fillStyle=color;
        const strength=vertical?level/100:clamp(level/100*count-i,0,1);if(strength>0){const filled=vertical?h*strength:h;paint.beginPath();paint.roundRect(x,vertical?top+h-filled:top,vertical?barWidth:barWidth*strength,filled,Math.min(3,barWidth*strength/2,filled/2));paint.fill()}}
      paint.globalAlpha=1;paint.strokeStyle=color;paint.lineWidth=1.5;paint.setLineDash([4,4]);paint.beginPath();
      if(vertical){const y=top+h*(1-Number(range.value)/100);paint.moveTo(0,y);paint.lineTo(width,y)}else{const x=clamp(Number(range.value)/100*width,1,width-1);paint.moveTo(x,top-8);paint.lineTo(x,top+h+8)}paint.stroke();paint.setLineDash([]);
      if(!vertical){paint.fillStyle=quiet;paint.globalAlpha=.45;paint.font='10px Inter, sans-serif';for(let i=0;i<=4;i++){paint.textAlign=i===0?'left':i===4?'right':'center';paint.fillText(String(i*25),i*width/4,Math.min(height-2,top+h+25))}if(active){paint.globalAlpha=.8;paint.fillStyle=color;paint.fillRect(clamp(peak/100*width,0,width-2),top,2,h)}paint.globalAlpha=1}

    }
  }
  function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);width=Math.max(1,r.width);height=Math.max(1,r.height);canvas.width=width*dpr;canvas.height=height*dpr;paint.setTransform(dpr,0,0,dpr,0,0);draw()}
  const color=m.querySelector('.nm-color');color.value=m.dataset.meter||'green';color.addEventListener('change',()=>{m.dataset.meter=color.value;draw();notifyBoardChanged('noise-color')});

  view.closest('label').hidden=true;color.closest('label').hidden=true;
  const controls=document.createElement('div');controls.className='nm-drawer-controls';m.append(controls);
  const drawer=document.createElement('div');drawer.className='timer-shape-shelf nm-drawer';drawer.setAttribute('popover','manual');drawer.setAttribute('role','group');document.body.append(drawer);let drawerFrame=0,drawerAnchor=null;
  const icons={single:'<rect x="9" y="2" width="6" height="20" rx="3"/>',horizontal:'<path d="M3 7h3v10H3zm5 0h3v10H8zm5 0h3v10h-3zm5 0h3v10h-3z"/>',vertical:'<path d="M4 15h3v6H4zm6-6h3v12h-3zm6-6h3v18h-3z"/>',waveform:'<path d="M2 13c4-14 5 14 10 0s6 9 10-3" fill="none" stroke="currentColor" stroke-width="2"/>'};
  const closeDrawer=()=>{drawer.hidePopover();cancelAnimationFrame(drawerFrame);controls.querySelectorAll('button').forEach(b=>b.setAttribute('aria-expanded','false'));drawerAnchor=null};
  const positionDrawer=()=>{if(!m.isConnected||!drawerAnchor){closeDrawer();return}const r=drawerAnchor.getBoundingClientRect();drawer.style.left=Math.max(8,Math.min(r.left+r.width/2-drawer.offsetWidth/2,innerWidth-drawer.offsetWidth-8))+'px';drawer.style.top=Math.max(8,Math.min(r.top-drawer.offsetHeight-8,innerHeight-drawer.offsetHeight-8))+'px';drawerFrame=requestAnimationFrame(positionDrawer)};
  for(const [kind,title,select] of [['display','Choose noise display',view],['color','Choose noise color',color]]){const toggle=document.createElement('button');toggle.type='button';toggle.className='custom-icon nm-'+kind+'-toggle';toggle.title=title;toggle.setAttribute('aria-label',title);toggle.setAttribute('aria-expanded','false');toggle.innerHTML=kind==='display'?'<svg viewBox="0 0 24 24" aria-hidden="true">'+icons.horizontal+'</svg>':'<i class="nm-color-dot" aria-hidden="true"></i>';controls.append(toggle);
    toggle.onclick=()=>{if(drawerAnchor===toggle){closeDrawer();return}closeDrawer();drawerAnchor=toggle;drawer.replaceChildren();drawer.setAttribute('aria-label',title);for(const option of select.options){const choice=document.createElement('button');choice.type='button';choice.setAttribute('aria-pressed',String(option.value===select.value));if(kind==='display')choice.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[option.value]+'</svg>';else{const swatch=document.createElement('i');swatch.className='timer-shelf-swatch';swatch.style.background={green:'#72aaa4',blue:'#789fbf',amber:'#caa367',rose:'#cb8d9c',purple:'#a398c4'}[option.value];choice.append(swatch)}const label=document.createElement('span');label.textContent=option.textContent;choice.append(label);choice.onclick=()=>{select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));notifyBoardChanged('noise-'+kind);closeDrawer();toggle.blur()};drawer.append(choice)}(document.fullscreenElement===m?m:document.body).append(drawer);drawer.showPopover();toggle.setAttribute('aria-expanded','true');positionDrawer()};
  }
  const outsideDrawer=e=>{if(!drawer.contains(e.target)&&!controls.contains(e.target))closeDrawer()};const escapeDrawer=e=>{if(e.key==='Escape'&&drawerAnchor){const anchor=drawerAnchor;closeDrawer();anchor.focus();e.stopPropagation()}};document.addEventListener('pointerdown',outsideDrawer,true);document.addEventListener('keydown',escapeDrawer,true);

  const observer=new ResizeObserver(resize);observer.observe(canvas);
  let lastView=view.value,wideSize=null;
  function settings(){if(view.value!==lastView){if(view.value==='single'){wideSize={width:m.style.width||m.offsetWidth+'px',height:m.style.height||m.offsetHeight+'px'};m.style.width='280px';m.style.height='420px'}else if(lastView==='single'&&wideSize){m.style.width=wideSize.width;m.style.height=wideSize.height}lastView=view.value}
color.value=m.dataset.meter||'green';m.dataset.noiseView=view.value;m.querySelector('.noise-threshold-value').textContent=range.value+'%';m.querySelector('.noise-sensitivity-value').textContent=sensitivity.value+'%';draw()}
  for(const input of [range,sensitivity,view])input.addEventListener('input',settings);view.addEventListener('change',settings);
  function stop(){generation++;pending=false;active=false;cancelAnimationFrame(frame);frame=0;stream?.getTracks().forEach(track=>track.stop());stream=null;if(context)context.close().catch(()=>{});context=analyser=null;level=peak=0;history.fill(0);value.textContent='—';status.textContent='Microphone off';button.textContent='Enable microphone';button.disabled=false;m.classList.remove('nm-live','is-loud');draw()}
  function loop(now){if(!active||!m.isConnected){if(active)stop();return}analyser.getByteTimeDomainData(samples);let sum=0;for(const sample of samples)sum+=((sample-128)/128)**2;const rms=Math.sqrt(sum/samples.length),raw=clamp((20*Math.log10(rms||.00001)+60)/60*Number(sensitivity.value),0,100);level+=(raw-level)*.16;peak=Math.max(level,peak-.12);history.push(level);history.shift();const loud=level>=Number(range.value);m.classList.toggle('is-loud',loud);if(now-lastLabel>120){value.textContent=Math.round(level)+'%';status.textContent=loud?'Time to lower our voices':level<25?'A calm room':'Listening to the room';lastLabel=now}draw();frame=requestAnimationFrame(loop)}
  button.onclick=async()=>{if(active||pending){stop();return}pending=true;const ticket=++generation;button.disabled=true;status.textContent='Waiting for microphone…';let requested=null;try{requested=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:false,autoGainControl:false}});if(disposed||ticket!==generation||!m.isConnected){requested.getTracks().forEach(t=>t.stop());return}stream=requested;context=new(window.AudioContext||window.webkitAudioContext)();await context.resume();if(disposed||ticket!==generation)return;analyser=context.createAnalyser();analyser.fftSize=2048;context.createMediaStreamSource(stream).connect(analyser);active=true;pending=false;button.disabled=false;button.textContent='Pause listening';m.classList.add('nm-live');frame=requestAnimationFrame(loop)}catch{requested?.getTracks().forEach(t=>t.stop());if(ticket!==generation)return;stop();status.textContent='Microphone unavailable. Check your browser permission.'}};
  const visibility=()=>{if(document.hidden)stop()};document.addEventListener('visibilitychange',visibility);
  m._boardGetState=()=>({version:1,threshold:Number(range.value),sensitivity:Number(sensitivity.value),view:view.value,wideSize});m._boardSetState=state=>{lastView=state?.view||view.value;wideSize=state?.wideSize||null;if(state?.threshold!==undefined)range.value=clamp(Number(state.threshold)||70,10,100);if(state?.sensitivity!==undefined)sensitivity.value=clamp(Number(state.sensitivity)||100,50,200);if(['horizontal','vertical','waveform','single'].includes(state?.view))view.value=state.view;settings()};
  const prior=m._deactivate;m._deactivate=()=>{closeDrawer();stop();prior?.()};const cleanup=m._cleanup;m._cleanup=()=>{disposed=true;closeDrawer();drawer.remove();document.removeEventListener('pointerdown',outsideDrawer,true);document.removeEventListener('keydown',escapeDrawer,true);stop();observer.disconnect();document.removeEventListener('visibilitychange',visibility);cleanup?.()};settings();resize();
}
window.TeacherTilesNoiseMeter=Object.freeze({setup});})();
