(()=>{'use strict';
function setup(m){
  const canvas=m.querySelector('.nm-canvas'),paint=canvas.getContext('2d'),button=m.querySelector('.noise-start'),status=m.querySelector('.nm-status'),value=m.querySelector('.nm-value'),range=m.querySelector('.noise-range'),sensitivity=m.querySelector('.noise-sensitivity'),view=m.querySelector('.noise-view-select');
  let stream=null,context=null,analyser=null,frame=0,active=false,pending=false,disposed=false,generation=0,level=0,width=300,height=180,lastLabel=0;const samples=new Uint8Array(1024),history=Array(64).fill(0);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function draw(){
    paint.clearRect(0,0,width,height);const color=level>=Number(range.value)?'#dc8b75':getComputedStyle(m).getPropertyValue('--meter-color').trim()||'#72aaa4',quiet=getComputedStyle(m).getPropertyValue('--module-text').trim()||'#23343b';
    if(view.value==='waveform'){
      paint.beginPath();history.forEach((v,i)=>{const x=i/(history.length-1)*width,y=height*.76-v/100*height*.6;i?paint.lineTo(x,y):paint.moveTo(x,y)});paint.lineTo(width,height);paint.lineTo(0,height);paint.closePath();const fill=paint.createLinearGradient(0,0,0,height);fill.addColorStop(0,color+'77');fill.addColorStop(1,color+'00');paint.fillStyle=fill;paint.fill();paint.beginPath();history.forEach((v,i)=>{const x=i/(history.length-1)*width,y=height*.76-v/100*height*.6;i?paint.lineTo(x,y):paint.moveTo(x,y)});paint.strokeStyle=color;paint.lineWidth=3;paint.lineJoin='round';paint.stroke();
    }else{
      const vertical=view.value==='vertical',count=32,gap=Math.min(4,width/96),barWidth=(width-gap*(count-1))/count;
      for(let i=0;i<count;i++){const t=i/(count-1),h=vertical?height*.8:height*(.18+.7*Math.sin(Math.PI*t)**.7),x=i*(barWidth+gap),y=(height-h)/2;paint.globalAlpha=.08;paint.fillStyle=quiet;paint.beginPath();paint.roundRect(x,y,barWidth,h,Math.min(4,barWidth/2));paint.fill();paint.globalAlpha=1;paint.fillStyle=color;
        const strength=vertical?clamp(level/100-t*.08,0,1):clamp(level/100*count-i,0,1);if(strength>0){const filled=vertical?h*strength:h;paint.globalAlpha=vertical?.45+.55*Math.sin(Math.PI*t):strength;paint.beginPath();paint.roundRect(x,vertical?y+h-filled:y,barWidth,filled,Math.min(4,barWidth/2,filled/2));paint.fill()}}
      paint.globalAlpha=1;const x=Number(range.value)/100*width;paint.setLineDash([3,5]);paint.strokeStyle=color+'88';paint.lineWidth=1;paint.beginPath();paint.moveTo(x,0);paint.lineTo(x,height);paint.stroke();paint.setLineDash([]);
    }
  }
  function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);width=Math.max(1,r.width);height=Math.max(1,r.height);canvas.width=width*dpr;canvas.height=height*dpr;paint.setTransform(dpr,0,0,dpr,0,0);draw()}
  const color=m.querySelector('.nm-color');color.value=m.dataset.meter||'green';color.addEventListener('change',()=>{m.dataset.meter=color.value;draw();notifyBoardChanged('noise-color')});
  const observer=new ResizeObserver(resize);observer.observe(canvas);
  function settings(){color.value=m.dataset.meter||'green';m.dataset.noiseView=view.value;m.querySelector('.noise-threshold-value').textContent=range.value+'%';m.querySelector('.noise-sensitivity-value').textContent=sensitivity.value+'%';draw()}
  for(const input of [range,sensitivity,view])input.addEventListener('input',settings);view.addEventListener('change',settings);
  function stop(){generation++;pending=false;active=false;cancelAnimationFrame(frame);frame=0;stream?.getTracks().forEach(track=>track.stop());stream=null;if(context)context.close().catch(()=>{});context=analyser=null;level=0;history.fill(0);value.textContent='—';status.textContent='Microphone off';button.textContent='Enable microphone';button.disabled=false;m.classList.remove('nm-live','is-loud');draw()}
  function loop(now){if(!active||!m.isConnected){if(active)stop();return}analyser.getByteTimeDomainData(samples);let sum=0;for(const sample of samples)sum+=((sample-128)/128)**2;const rms=Math.sqrt(sum/samples.length),raw=clamp((20*Math.log10(rms||.00001)+60)/60*Number(sensitivity.value),0,100);level+=(raw-level)*.16;history.push(level);history.shift();const loud=level>=Number(range.value);m.classList.toggle('is-loud',loud);if(now-lastLabel>120){value.textContent=Math.round(level)+'%';status.textContent=loud?'Time to lower our voices':level<25?'A calm room':'Listening to the room';lastLabel=now}draw();frame=requestAnimationFrame(loop)}
  button.onclick=async()=>{if(active||pending){stop();return}pending=true;const ticket=++generation;button.disabled=true;status.textContent='Waiting for microphone…';let requested=null;try{requested=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:false,autoGainControl:false}});if(disposed||ticket!==generation||!m.isConnected){requested.getTracks().forEach(t=>t.stop());return}stream=requested;context=new(window.AudioContext||window.webkitAudioContext)();await context.resume();if(disposed||ticket!==generation)return;analyser=context.createAnalyser();analyser.fftSize=2048;context.createMediaStreamSource(stream).connect(analyser);active=true;pending=false;button.disabled=false;button.textContent='Pause listening';m.classList.add('nm-live');frame=requestAnimationFrame(loop)}catch{requested?.getTracks().forEach(t=>t.stop());if(ticket!==generation)return;stop();status.textContent='Microphone unavailable. Check your browser permission.'}};
  const visibility=()=>{if(document.hidden)stop()};document.addEventListener('visibilitychange',visibility);
  m._boardGetState=()=>({version:1,threshold:Number(range.value),sensitivity:Number(sensitivity.value),view:view.value});m._boardSetState=state=>{if(state?.threshold!==undefined)range.value=clamp(Number(state.threshold)||70,10,100);if(state?.sensitivity!==undefined)sensitivity.value=clamp(Number(state.sensitivity)||100,50,200);if(['horizontal','vertical','waveform'].includes(state?.view))view.value=state.view;settings()};
  const prior=m._deactivate;m._deactivate=()=>{stop();prior?.()};const cleanup=m._cleanup;m._cleanup=()=>{disposed=true;stop();observer.disconnect();document.removeEventListener('visibilitychange',visibility);cleanup?.()};settings();resize();
}
window.TeacherTilesNoiseMeter=Object.freeze({setup});})();
