const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
const labels={new:'New','in-progress':'In Progress',complete:'Complete'};
export function createBugReports(call){
 const element=el('section');element.id='portal-bug-reports';element.hidden=true;
 const header=el('div'),title=el('h1','Bug Reports'),filter=el('select'),refresh=el('button','Refresh'),status=el('p'),list=el('div'),more=el('button','Load more');header.className='bug-report-toolbar';filter.setAttribute('aria-label','Filter bug reports');
 for(const [value,name] of Object.entries({all:'All reports',...labels})){const option=el('option',name);option.value=value;filter.append(option);}header.append(title,filter,refresh);list.className='bug-report-list';more.hidden=true;status.setAttribute('role','status');element.append(header,status,list,more);let cursor=null,generation=0;const cache=new Map();
 const request=async data=>(await call('developerBugReports',data)).data;
 async function load(force=false,append=false){const ticket=++generation,key=filter.value;if(force)cache.clear();refresh.disabled=more.disabled=true;status.textContent='Loading reports…';try{let data=!append&&cache.get(key);if(!data||Date.now()-data.at>300000){data={...(await request({action:'list',status:key,cursor:append?cursor:null})),at:Date.now()};if(!append)cache.set(key,data);}if(ticket!==generation)return;if(!append)list.replaceChildren();for(const report of data.items){const row=el('button');row.className='bug-report-row';row.append(el('strong',report.title),el('span',report.category+' · '+report.authorEmail),el('small',labels[report.status]));row.dataset.status=report.status;row.onclick=()=>detail(report.id);list.append(row);}cursor=data.cursor;more.hidden=!cursor;status.textContent=list.children.length?'':'No reports here.';}catch(error){if(ticket===generation)status.textContent=error.message;}finally{if(ticket===generation)refresh.disabled=more.disabled=false;}}
 async function detail(id){const d=el('dialog');d.className='bug-report-detail';const close=el('button','Close'),message=el('p','Loading…');close.onclick=()=>d.close();d.append(close,message);document.body.append(d);d.onclose=()=>d.remove();d.onclick=e=>{if(e.target===d)d.close();};d.showModal();const ticket=generation;
  try{const {report}=await request({action:'detail',id});if(!d.isConnected||ticket!==generation){d.close();return;}message.textContent=report.category+' · '+report.authorEmail+' · '+new Date(report.createdAt).toLocaleString();d.prepend(el('h2',report.title));const description=el('p',report.description);description.className='bug-report-description';d.append(description,el('small',report.browser||''));const controls=el('div');controls.className='bug-report-toolbar';for(const [value,name] of Object.entries(labels)){const b=el('button',name);b.disabled=value===report.status;b.onclick=async()=>{controls.querySelectorAll('button').forEach(n=>n.disabled=true);try{await request({action:'update',id,status:value,revision:report.revision});d.close();load(true);}catch(e){message.textContent=e.message;controls.querySelectorAll('button').forEach(n=>n.disabled=false);}};controls.append(b);}d.append(controls);}catch(e){message.textContent=e.message;}
 }
 refresh.onclick=()=>load(true);filter.onchange=()=>load();more.onclick=()=>load(false,true);
 return {element,load,reset(){generation++;cache.clear();list.replaceChildren();document.querySelectorAll('.bug-report-detail').forEach(d=>d.close());}};
}
