export const ticketStatuses={new:'Reported','in-progress':'In Progress',complete:'Closed'};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
export function ticketBadge(status){const n=el('span',ticketStatuses[status]||status,'ticket-status-badge');n.dataset.status=status;return n;}
export function openTicketThread({id,request,admin=false,onChange=()=>{},onRead=()=>{}}){
 if(!document.querySelector('[data-ticket-thread-style]')){const css=el('link');css.rel='stylesheet';css.href=new URL('./ticket-thread.css?v=20260926-ticket-actions',import.meta.url).href;css.dataset.ticketThreadStyle='';document.head.append(css);}
 const dialog=el('dialog',null,'ticket-thread'),header=el('header'),title=el('h2','Ticket'),close=el('button','×','ticket-thread-close'),meta=el('p',null,'ticket-thread-meta'),original=el('article',null,'ticket-thread-original'),log=el('div',null,'ticket-thread-log'),notice=el('p'),tools=el('div',null,'ticket-thread-tools'),refresh=el('button','Refresh Conversation'),older=el('button','Load Older Updates'),form=el('form'),input=el('textarea'),send=el('button',admin?'Send Update':'Send Reply'),status=el('select');
 close.type='button';close.setAttribute('aria-label','Close ticket');close.onclick=()=>dialog.close();header.append(title,close);notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');input.required=!admin;input.maxLength=4000;input.rows=3;input.placeholder=admin?'Reply, ask a question, or explain the resolution…':'Write a reply…';input.setAttribute('aria-label','Ticket reply');send.type='submit';status.setAttribute('aria-label','Ticket status');for(const [value,name] of Object.entries(ticketStatuses)){const o=el('option',name);o.value=value;status.append(o);}form.append(input);if(admin)form.append(status);form.append(send);tools.append(refresh,older);dialog.append(header,meta,original,tools,log,form,notice);document.body.append(dialog);dialog.showModal();dialog.onclick=e=>{if(e.target===dialog)dialog.close();};dialog.onclose=()=>{generation++;dialog.remove();};
 let readRevision=null,report=null,cursor=null,generation=0,busy=false,requestId=null;form.oninput=()=>{requestId=null;};
 function entry(event){const n=el('article',null,'ticket-thread-entry');n.dataset.role=event.role;n.append(el('small',(event.role==='developer'?'TeacherTiles Support':'You / ticket author')+' · '+new Date(event.at).toLocaleString()));if(event.message)n.append(el('p',event.message));if(event.statusChanged)n.append(el('div',(ticketStatuses[event.fromStatus]||event.fromStatus)+' → '+ticketStatuses[event.status],'ticket-thread-change'));return n;}
 async function load(append=false){const token=++generation;refresh.disabled=older.disabled=true;send.disabled=true;notice.textContent='Loading conversation…';try{const data=await request({action:'detail',id,cursor:append?cursor:null});if(token!==generation||!dialog.isConnected)return;report=data.report;if(readRevision!==report.revision){readRevision=report.revision;void onRead(report);}title.textContent=report.title;meta.replaceChildren(ticketBadge(report.status),el('span',report.category+' · '+new Date(report.createdAt).toLocaleString()));original.replaceChildren(el('small','Original ticket'),el('p',report.description));status.value=report.status;if(!append)log.replaceChildren();const events=[...(data.events||[])].reverse().map(entry);if(append)log.prepend(...events);else log.append(...events);cursor=data.cursor;older.hidden=!cursor;notice.textContent=report.status==='complete'&&!admin?'Replying will reopen this ticket.':'';}catch(e){if(token===generation)notice.textContent=e.message;}finally{if(token===generation){refresh.disabled=older.disabled=false;send.disabled=!report;}}}
 refresh.onclick=()=>load();older.onclick=()=>load(true);
 form.onsubmit=async e=>{e.preventDefault();if(busy||!report||!form.reportValidity())return;busy=true;send.disabled=refresh.disabled=older.disabled=true;input.disabled=status.disabled=true;notice.textContent='Sending…';requestId ||= Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,'0')).join('');const token=generation;try{await request({action:admin?'update':'reply',id,message:input.value,requestId,...(admin?{status:status.value,revision:report.revision}:{})});if(token!==generation||!dialog.isConnected)return;input.value='';requestId=null;onChange();await load();}catch(e){if(token===generation)notice.textContent=e.message;}finally{busy=false;if(dialog.isConnected){send.disabled=refresh.disabled=older.disabled=false;input.disabled=status.disabled=false;}}};
 if(admin){const remove=el('button','Delete Ticket','ticket-thread-delete');remove.type='button';remove.onclick=()=>{const confirm=el('dialog',null,'ticket-thread'),heading=el('h2','Permanently Delete This Ticket?'),copy=el('p','This removes the ticket, all replies, status history, and its notifications for both the user and developers.'),cancel=el('button','Cancel'),yes=el('button','Delete Permanently','ticket-thread-delete-confirm');cancel.onclick=()=>confirm.close();yes.onclick=async()=>{yes.disabled=true;try{await request({action:'delete',id,confirm:true});confirm.close();dialog.close();onChange();}catch(e){copy.textContent=e.message;yes.disabled=false;}};confirm.append(heading,copy,cancel,yes);document.body.append(confirm);confirm.onclose=()=>confirm.remove();confirm.showModal();};tools.append(remove);}
 load();return dialog;
}
