(()=>{'use strict';
const names='aliceblue antiquewhite aqua aquamarine azure beige bisque black blanchedalmond blue blueviolet brown burlywood cadetblue chartreuse chocolate coral cornflowerblue cornsilk crimson cyan darkblue darkcyan darkgoldenrod darkgray darkgreen darkgrey darkkhaki darkmagenta darkolivegreen darkorange darkorchid darkred darksalmon darkseagreen darkslateblue darkslategray darkslategrey darkturquoise darkviolet deeppink deepskyblue dimgray dimgrey dodgerblue firebrick floralwhite forestgreen fuchsia gainsboro ghostwhite gold goldenrod gray green greenyellow grey honeydew hotpink indianred indigo ivory khaki lavender lavenderblush lawngreen lemonchiffon lightblue lightcoral lightcyan lightgoldenrodyellow lightgray lightgreen lightgrey lightpink lightsalmon lightseagreen lightskyblue lightslategray lightslategrey lightsteelblue lightyellow lime limegreen linen magenta maroon mediumaquamarine mediumblue mediumorchid mediumpurple mediumseagreen mediumslateblue mediumspringgreen mediumturquoise mediumvioletred midnightblue mintcream mistyrose moccasin navajowhite navy oldlace olive olivedrab orange orangered orchid palegoldenrod palegreen paleturquoise palevioletred papayawhip peachpuff peru pink plum powderblue purple rebeccapurple red rosybrown royalblue saddlebrown salmon sandybrown seagreen seashell sienna silver skyblue slateblue slategray slategrey snow springgreen steelblue tan teal thistle tomato turquoise violet wheat white whitesmoke yellow yellowgreen'.split(' ');
function setup(m){const wheel=m.querySelector('.color-wheel'),ctx=wheel.getContext('2d'),hex=m.querySelector('.color-hex'),brightness=m.querySelector('.color-value'),status=m.querySelector('.color-status');let color='#6f8fb7',hue=0,saturation=1,abort=null;
const named={};for(const name of names){ctx.fillStyle=name;named[ctx.fillStyle.toLowerCase()]=name}
function set(value){if(/^#[0-9a-f]{3}$/i.test(value))value='#'+value.slice(1).split('').map(c=>c+c).join('');if(!/^#[0-9a-f]{6}$/i.test(value))return false;color=value.toLowerCase();hex.value=color.toUpperCase();m.querySelector('.color-large').style.background=color;m.querySelector('.color-code').textContent=color.toUpperCase();m.querySelector('.color-name').textContent=named[color]||'Custom color';return true}
function rgb(h,s,v){const f=n=>{const k=(n+h*6)%6;return Math.round(255*v*(1-s*Math.max(0,Math.min(k,4-k,1))))};return '#'+[f(5),f(3),f(1)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function draw(){const image=ctx.createImageData(220,220);for(let y=0;y<220;y++)for(let x=0;x<220;x++){const dx=x-110,dy=y-110,r=Math.hypot(dx,dy)/108;if(r>1)continue;const c=rgb((Math.atan2(dy,dx)/Math.PI/2+1)%1,r,Number(brightness.value)/100);const i=(y*220+x)*4;image.data[i]=parseInt(c.slice(1,3),16);image.data[i+1]=parseInt(c.slice(3,5),16);image.data[i+2]=parseInt(c.slice(5,7),16);image.data[i+3]=255}ctx.putImageData(image,0,0)}
function choose(e){const r=wheel.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*220-110,y=(e.clientY-r.top)/r.height*220-110;hue=(Math.atan2(y,x)/Math.PI/2+1)%1;saturation=Math.min(1,Math.hypot(x,y)/108);set(rgb(hue,saturation,Number(brightness.value)/100));notifyBoardChanged('color-picker')}
wheel.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();wheel.setPointerCapture(e.pointerId);choose(e)});wheel.addEventListener('pointermove',e=>{if(wheel.hasPointerCapture(e.pointerId))choose(e)});wheel.addEventListener('pointerup',e=>{if(wheel.hasPointerCapture(e.pointerId))wheel.releasePointerCapture(e.pointerId)});wheel.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();hue=(hue+(e.key==='ArrowLeft'?-.02:e.key==='ArrowRight'?.02:0)+1)%1;saturation=Math.max(0,Math.min(1,saturation+(e.key==='ArrowUp'?.05:e.key==='ArrowDown'?-.05:0)));set(rgb(hue,saturation,Number(brightness.value)/100));notifyBoardChanged('color-picker')});
hex.addEventListener('change',()=>{if(set(hex.value.trim())){status.textContent='';notifyBoardChanged('color-picker')}else status.textContent='Enter a hex color such as #FF8800.'});brightness.addEventListener('input',()=>{draw();set(rgb(hue,saturation,Number(brightness.value)/100));notifyBoardChanged('color-picker')});
const drop=m.querySelector('.color-eyedropper');drop.innerHTML='<svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m14 3 7 7-10 10H4v-7zM12 5l7 7M4 20l-2 2"/></svg> Pick from screen';drop.addEventListener('click',async()=>{if(!window.EyeDropper){status.textContent='Screen picking needs a browser with eyedropper support, such as Chrome or Edge. You can still use the wheel or hex code.';return}abort?.abort();abort=new AbortController();try{const result=await new EyeDropper().open({signal:abort.signal});if(m.isConnected){set(result.sRGBHex);status.textContent='';notifyBoardChanged('color-picker')}}catch(e){if(e.name!=='AbortError')status.textContent='Screen picking is unavailable. Try the wheel or hex code.'}});
m._boardGetState=()=>({color});m._boardSetState=s=>{set(s?.color||'#6f8fb7')};m._deactivate=()=>abort?.abort();m._cleanup=()=>abort?.abort();draw();set(color)}window.TeacherTilesColorpicker={setup};})();
