import { readFileSync } from 'node:fs';
import { createHash, randomBytes } from 'node:crypto';
import { initializeTestEnvironment, assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import { doc, getDoc, getDocs, collection, setDoc, updateDoc, deleteDoc, writeBatch } from 'firebase/firestore';
import assert from 'node:assert/strict';
const projectId = 'demo-wigs-tests';
const env = await initializeTestEnvironment({ projectId, firestore: { host: '127.0.0.1', port: 8085, rules: readFileSync('firestore.rules', 'utf8') } });
const email = name => [name, 'example.invalid'].join('@');
const hash = name => createHash('sha256').update(email(name).toLowerCase()).digest('hex');
const signed = (uid, address = uid, extra = {}) => env.authenticatedContext(uid, { email: email(address), email_verified: true, firebase: { sign_in_provider: 'google.com' }, ...extra }).firestore();
const teacher = signed('teacher-a'), other = signed('teacher-b'), student = signed('student-user', 'child'), sibling = signed('sibling-user', 'sibling'), anonymous = env.unauthenticatedContext().firestore();
const classPath = 'classes/teacher-a';
const studentPath = classPath + '/students/child-1';
const encrypted = () => ({ version: 1, iv: randomBytes(12).toString('base64'), ciphertext: randomBytes(64).toString('base64') });
const vaultKey = () => ({ version: 1, keyMaterial: randomBytes(32).toString('base64') });
const studentData = address => ({ ...encrypted(), emailHash: hash(address) });
let checks = 0;
const ok = async p => { await assertSucceeds(p); checks++; };
const no = async p => { await assertFails(p); checks++; };
const assign = async (db, owner, id, address) => {
  await ok(setDoc(doc(db, 'classes/' + owner + '/keys/student_' + id), vaultKey()));
  const batch = writeBatch(db);
  batch.set(doc(db, 'classes/' + owner + '/students/' + id), studentData(address));
  batch.set(doc(db, 'studentAccess', hash(address)), { ownerId: owner, studentId: id });
  return batch.commit();
};
try {
  await env.clearFirestore();
  await ok(getDoc(doc(student, 'studentAccess', hash('child'))));
  await ok(getDoc(doc(student, 'studentLinks', email('child'))));
  await no(getDoc(doc(anonymous, classPath)));
  await no(setDoc(doc(signed('unverified', 'unverified', { email_verified: false }), 'classes/unverified/keys/shared'), vaultKey()));
  await no(setDoc(doc(signed('password-user', 'password-user', { firebase: { sign_in_provider: 'password' } }), 'classes/password-user/keys/shared'), vaultKey()));
  await ok(setDoc(doc(teacher, classPath + '/keys/shared'), vaultKey()));
  await ok(setDoc(doc(teacher, classPath), encrypted()));
  await ok(setDoc(doc(other, 'classes/teacher-b/keys/shared'), vaultKey()));
  await ok(setDoc(doc(other, 'classes/teacher-b'), encrypted()));
  await no(getDoc(doc(other, classPath)));
  await no(getDocs(collection(teacher, 'classes')));
  await no(getDocs(collection(teacher, classPath + '/keys')));
  await no(getDoc(doc(other, classPath + '/keys/shared')));
  await no(getDoc(doc(anonymous, classPath + '/keys/shared')));
  await no(updateDoc(doc(teacher, classPath + '/keys/shared'), vaultKey()));
  await no(deleteDoc(doc(teacher, classPath + '/keys/shared')));
  await no(setDoc(doc(teacher, classPath + '/keys/bad'), { version: 1, keyMaterial: 'bad' }));
  await no(setDoc(doc(teacher, studentPath), studentData('child')));
  await ok(assign(teacher, 'teacher-a', 'child-1', 'child'));
  await ok(assign(teacher, 'teacher-a', 'child-2', 'sibling'));
  await ok(getDoc(doc(student, studentPath)));
  await ok(getDoc(doc(student, classPath + '/keys/shared')));
  await ok(getDoc(doc(student, classPath + '/keys/student_child-1')));
  await ok(getDoc(doc(teacher, classPath + '/keys/student_child-1')));
  await no(getDoc(doc(student, classPath + '/keys/student_child-2')));
  await no(getDoc(doc(sibling, classPath + '/keys/student_child-1')));
  await no(getDoc(doc(other, classPath + '/keys/student_child-1')));
  await no(getDoc(doc(anonymous, classPath + '/keys/student_child-1')));
  await no(setDoc(doc(student, classPath + '/keys/student_fake'), vaultKey()));
  await no(getDoc(doc(student, classPath + '/students/child-2')));
  await no(getDoc(doc(sibling, studentPath)));
  await no(getDocs(collection(student, classPath + '/students')));
  await no(getDocs(collection(student, 'studentAccess')));
  await no(getDoc(doc(other, 'studentAccess', hash('child'))));
  await no(getDoc(doc(anonymous, 'studentAccess', hash('child'))));
  await no(setDoc(doc(student, 'classes/student-user/keys/shared'), vaultKey()));
  await no(setDoc(doc(student, studentPath), studentData('child')));
  await no(setDoc(doc(other, studentPath), studentData('child')));
  await ok(setDoc(doc(teacher, studentPath), studentData('child')));
  await no(assign(other, 'teacher-b', 'stolen', 'child'));
  await no(setDoc(doc(student, 'studentAccess', hash('other')), { ownerId: 'student-user', studentId: 'fake' }));
  await no(setDoc(doc(student, classPath), encrypted()));

  // No plaintext payload fields or readable email document paths can be added.
  await no(updateDoc(doc(teacher, studentPath), { name: 'Plaintext' }));
  await no(updateDoc(doc(teacher, studentPath), { email: email('child') }));
  await no(updateDoc(doc(teacher, studentPath), { imageKey: 'preset:yes' }));
  await no(setDoc(doc(teacher, classPath), { title: 'Plaintext', description: 'Plaintext' }));
  await no(setDoc(doc(teacher, 'studentLinks', email('new')), { ownerId: 'teacher-a', studentId: 'child-1' }));
  await no(setDoc(doc(teacher, classPath), { ...encrypted(), iv: 'invalid' }));
  await no(setDoc(doc(teacher, classPath), { ...encrypted(), version: 2 }));
  await ok(setDoc(doc(teacher, classPath + '/questions/q1'), encrypted()));
  await ok(getDoc(doc(student, classPath + '/questions/q1')));
  await no(setDoc(doc(student, classPath + '/questions/q2'), encrypted()));
  await no(setDoc(doc(teacher, classPath + '/questions/q2'), { ...encrypted(), prompt: 'Plaintext' }));
  await ok(setDoc(doc(teacher, classPath + '/answers/a1'), encrypted()));
  await no(setDoc(doc(other, classPath + '/answers/a2'), encrypted()));
  const responsePath = studentPath + '/responses/2026-09-09';
  await ok(setDoc(doc(student, responsePath), encrypted()));
  await ok(getDoc(doc(teacher, responsePath)));
  await no(getDoc(doc(sibling, responsePath)));
  await no(setDoc(doc(student, responsePath), encrypted()));
  await no(setDoc(doc(teacher, responsePath), encrypted()));
  await no(deleteDoc(doc(student, responsePath)));
  await no(setDoc(doc(student, classPath + '/students/child-2/responses/2026-09-09'), encrypted()));
  await no(setDoc(doc(student, studentPath + '/responses/2026-09-10'), { ...encrypted(), items: [] }));
  await no(setDoc(doc(student, studentPath + '/responses/2026-09-10'), { ...encrypted(), ciphertext: 'A'.repeat(950004) }));
  await ok(setDoc(doc(student, studentPath + '/responses/2026-09-10'), encrypted()));
  await no(deleteDoc(doc(teacher, 'studentAccess', hash('child'))));
  await no(deleteDoc(doc(teacher, studentPath)));
  let batch = writeBatch(teacher);
  batch.set(doc(teacher, studentPath), studentData('new-child'));
  batch.delete(doc(teacher, 'studentAccess', hash('child')));
  batch.set(doc(teacher, 'studentAccess', hash('new-child')), { ownerId: 'teacher-a', studentId: 'child-1' });
  await ok(batch.commit());
  await no(getDoc(doc(student, studentPath)));
  await no(getDoc(doc(student, classPath + '/keys/student_child-1')));
  await ok(getDoc(doc(signed('new-child-user', 'new-child'), studentPath)));
  await ok(getDoc(doc(signed('new-child-user', 'new-child'), classPath + '/keys/student_child-1')));

  // Seed an old plaintext class, then exercise the same migration writes as the app.
  const legacyPath = classPath + '/students/legacy';
  await env.withSecurityRulesDisabled(async context => {
    const db = context.firestore();
    await setDoc(doc(db, legacyPath), { id: 'legacy', name: 'Synthetic legacy learner', email: email('legacy'), imageKey: null, currentScore: null, goalScore: null });
    await setDoc(doc(db, 'studentLinks', email('legacy')), { ownerId: 'teacher-a', studentId: 'legacy' });
    await setDoc(doc(db, legacyPath + '/responses/2026-01-01'), { localDate: '2026-01-01', items: [] });
  });
  const legacyUser = signed('legacy-user', 'legacy');
  await ok(getDoc(doc(legacyUser, legacyPath)));
  await no(setDoc(doc(legacyUser, 'classes/legacy-user/keys/shared'), vaultKey()));
  await ok(setDoc(doc(teacher, classPath + '/keys/student_legacy'), vaultKey()));
  await ok(setDoc(doc(teacher, legacyPath + '/responses/2026-01-01'), encrypted()));
  await no(setDoc(doc(teacher, legacyPath + '/responses/2026-01-01'), encrypted()));
  await no(deleteDoc(doc(teacher, 'studentLinks', email('legacy'))));
  batch = writeBatch(teacher);
  batch.set(doc(teacher, legacyPath), studentData('legacy'));
  batch.set(doc(teacher, 'studentAccess', hash('legacy')), { ownerId: 'teacher-a', studentId: 'legacy' });
  batch.delete(doc(teacher, 'studentLinks', email('legacy')));
  await ok(batch.commit());
  await ok(getDoc(doc(legacyUser, legacyPath)));
  await ok(getDoc(doc(legacyUser, classPath + '/keys/student_legacy')));
  await no(getDoc(doc(sibling, classPath + '/keys/student_legacy')));
  await no(setDoc(doc(teacher, legacyPath), { id: 'legacy', name: 'Plaintext', email: email('legacy') }));

  // A hashed assignment must never override an existing legacy assignment.
  await env.withSecurityRulesDisabled(async context => {
    const db = context.firestore();
    await setDoc(doc(db, 'studentLinks', email('collision')), { ownerId: 'teacher-a', studentId: 'legacy' });
    await setDoc(doc(db, 'studentAccess', hash('collision')), { ownerId: 'teacher-b', studentId: 'stolen' });
  });
  const collision = signed('collision-user', 'collision');
  await ok(getDoc(doc(collision, legacyPath)));
  await no(getDoc(doc(collision, 'classes/teacher-b/keys/shared')));
  assert(checks > 60);
  console.log(checks + ' Firestore encrypted-data security checks passed.');
} finally {
  await env.cleanup();
}
