/* A deformable 3D lattice, with perspective rendering and surface picking. */
(()=>{'use strict';
function setup(m){
 const canvas=m.querySelector('.squishy-canvas'),gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:true});
 if(!gl){const message=document.createElement('p');message.textContent='3D Squishy needs WebGL enabled in your browser.';canvas.replaceWith(message);return;}
 const N=5,nodes=[],links=[],tris=[],idx=(x,y,z)=>x+N*y+N*N*z;
 for(let z=0;z<N;z++)for(let y=0;y<N;y++)for(let x=0;x<N;x++){const raw=[x,y,z].map(v=>(v/(N-1)*2-1)*.9),core=raw.map(v=>Math.max(-.68,Math.min(.68,v))),delta=raw.map((v,i)=>v-core[i]),len=Math.hypot(...delta)||1,r=core.map((v,i)=>v+delta[i]/len*.22);nodes.push({r,p:[...r],old:[...r]});}
 for(let a=0;a<nodes.length;a++)for(let b=a+1;b<nodes.length;b++){const d=Math.hypot(...nodes[a].r.map((v,i)=>v-nodes[b].r[i]));if(d<.83)links.push([a,b,d]);}
 for(let axis=0;axis<3;axis++)for(const side of [0,N-1])for(let i=0;i<N-1;i++)for(let j=0;j<N-1;j++){const at=(a,b)=>{const c=[];c[axis]=side;c[(axis+1)%3]=a;c[(axis+2)%3]=b;return idx(...c)};let q=[at(i,j),at(i+1,j),at(i+1,j+1),at(i,j+1)];if(side===0)q=q.reverse();tris.push([q[0],q[1],q[2]],[q[0],q[2],q[3]]);}
 const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 const vs=shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 n;varying vec3 normal;varying vec3 pos;uniform float aspect;void main(){normal=n;pos=p;float z=6.0-p.z;gl_Position=vec4(p.x*2.6/aspect,p.y*2.6,(z-0.1)*1.01-0.202,z);}');
 const fs=shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 normal;varying vec3 pos;void main(){vec3 n=normalize(normal);if(!gl_FrontFacing)n=-n;vec3 light=normalize(vec3(-.5,.85,1.4));vec3 view=normalize(vec3(0.,0.,6.)-pos);float diffuse=max(dot(n,light),0.);float spec=pow(max(dot(n,normalize(light+view)),0.),65.);float rim=pow(1.-abs(dot(n,view)),3.);vec3 col=mix(vec3(.015,.48,.57),vec3(.20,.84,.83),diffuse);col+=vec3(.72,.94,.92)*spec*.8+vec3(.25,.48,.44)*rim*.35;col+=vec3(.25,.65,.64)*pow(max(dot(n,normalize(vec3(.7,.6,1.))),0.),12.)*.18;gl_FragColor=vec4(col,.76+rim*.12);}');
 const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(const [name,offset] of [['p',0],['n',12]]){const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,24,offset);}gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);
 let yaw=.65,pitch=.35,frame=0,disposed=false,last=0,accumulator=0,grab=-1,grabDepth=0,rotating=false,previous=null,target=null,quiet=0;
 const turn=v=>{const x=v[0]*Math.cos(yaw)+v[2]*Math.sin(yaw),z=-v[0]*Math.sin(yaw)+v[2]*Math.cos(yaw);return[x,v[1]*Math.cos(pitch)-z*Math.sin(pitch),v[1]*Math.sin(pitch)+z*Math.cos(pitch)];};
 const unturn=v=>{const y=v[1]*Math.cos(pitch)+v[2]*Math.sin(pitch),z=-v[1]*Math.sin(pitch)+v[2]*Math.cos(pitch);return[v[0]*Math.cos(yaw)-z*Math.sin(yaw),y,v[0]*Math.sin(yaw)+z*Math.cos(yaw)];};
 function draw(){const w=Math.max(1,canvas.clientWidth),h=Math.max(1,canvas.clientHeight),dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniform1f(gl.getUniformLocation(program,'aspect'),w/h);
 const normals=nodes.map(()=>[0,0,0]);for(const [a,b,c] of tris){const u=nodes[b].p.map((v,i)=>v-nodes[a].p[i]),v=nodes[c].p.map((v,i)=>v-nodes[a].p[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];for(const k of [a,b,c])for(let i=0;i<3;i++)normals[k][i]+=n[i];}const data=[];for(const face of tris)for(const id of face)data.push(...turn(nodes[id].p),...turn(normals[id]));gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,data.length/6);
 }
 function step(){const before=nodes.map(n=>[...n.p]);let energy=0;const center=[0,0,0];for(const n of nodes)for(let i=0;i<3;i++)center[i]+=n.p[i]/nodes.length;
 for(const n of nodes){for(let i=0;i<3;i++){const velocity=(n.p[i]-n.old[i])*.975;n.old[i]=n.p[i];n.p[i]+=velocity+(center[i]+n.r[i]-n.p[i])*.022+(i===1?-.0015:0);energy+=velocity*velocity;}}
 for(let pass=0;pass<5;pass++){for(const [a,b,rest] of links){const u=nodes[a].p,v=nodes[b].p,d=u.map((x,i)=>v[i]-x),length=Math.hypot(...d)||1,c=(length-rest)/length*.28;for(let i=0;i<3;i++){u[i]+=d[i]*c;v[i]-=d[i]*c;}}
 if(grab>=0&&target){const n=nodes[grab];for(let i=0;i<3;i++)n.p[i]+=(target[i]-n.p[i])*.55;}
 for(const n of nodes){if(n.p[1]<-1.18){n.p[1]=-1.18;n.old[1]=n.p[1]-(n.old[1]-n.p[1])*.22;n.old[0]+=(n.p[0]-n.old[0])*.3;n.old[2]+=(n.p[2]-n.old[2])*.3;}n.p[0]=Math.max(-1.9,Math.min(1.9,n.p[0]));n.p[1]=Math.min(1.85,n.p[1]);n.p[2]=Math.max(-1.7,Math.min(1.7,n.p[2]));}}
 return nodes.reduce((total,n,k)=>total+n.p.reduce((sum,v,i)=>sum+(v-before[k][i])**2,0),0);}
 function tick(now){frame=0;if(disposed||document.hidden||!m.isConnected)return;accumulator+=Math.min(.05,(now-last)/1000||1/60);last=now;let energy=0;while(accumulator>=1/120){energy=step();accumulator-=1/120;}draw();quiet=energy<.00003&&grab<0?quiet+1:0;if(quiet<90||grab>=0)frame=requestAnimationFrame(tick);}
 function wake(){quiet=0;if(!frame&&!disposed){last=performance.now();frame=requestAnimationFrame(tick);}}
 const point=e=>{const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2,r.width/r.height];};
 canvas.title='Drag to stretch and toss · Shift-drag or drag empty space to rotate';
 canvas.setAttribute('aria-label','3D gel cube. Drag the cube to stretch and throw. Drag empty space or Shift-drag to rotate. Arrow keys rotate; Enter squishes.');
 canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==2)return;e.preventDefault();e.stopPropagation();canvas.setPointerCapture(e.pointerId);const [x,y,aspect]=point(e);let selected=-1,depth=-Infinity;const projected=nodes.map(n=>{const p=turn(n.p),z=6-p[2];return[p[0]*2.6/aspect/z,p[1]*2.6/z,p[2]]});for(const face of tris){const [a,b,c]=face.map(i=>projected[i]),den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<1e-8)continue;const u=((b[1]-c[1])*(x-c[0])+(c[0]-b[0])*(y-c[1]))/den,v=((c[1]-a[1])*(x-c[0])+(a[0]-c[0])*(y-c[1]))/den,w=1-u-v,z=u*a[2]+v*b[2]+w*c[2];if(u>=0&&v>=0&&w>=0&&z>depth){depth=z;selected=face[[u,v,w].indexOf(Math.max(u,v,w))];}}rotating=e.shiftKey||e.button===2||selected<0;previous=[e.clientX,e.clientY];grab=rotating?-1:selected;if(grab>=0){m._playSquish?.();target=[...nodes[grab].p];grabDepth=turn(target)[2];}wake();});
 canvas.addEventListener('pointermove',e=>{if(!previous)return;e.preventDefault();if(rotating){yaw+=(e.clientX-previous[0])*.012;pitch=Math.max(-1.2,Math.min(1.2,pitch+(e.clientY-previous[1])*.012));draw();}else if(grab>=0){const [x,y,aspect]=point(e),z=grabDepth;target=unturn([x*(6-z)*aspect/2.6,y*(6-z)/2.6,z]).map(v=>Math.max(-2,Math.min(2,v)));}previous=[e.clientX,e.clientY];wake();});
 const release=()=>{grab=-1;previous=null;target=null;rotating=false;wake();};for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,release);canvas.addEventListener('contextmenu',e=>e.preventDefault());
 canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter'].includes(e.key)){e.preventDefault();e.stopPropagation();if(e.key==='Enter'){if(e.repeat)return;m._playSquish?.();for(const n of nodes){n.p[1]*=.65;n.p[0]*=1.15;}}else if(e.key==='ArrowLeft')yaw-=.15;else if(e.key==='ArrowRight')yaw+=.15;else pitch+=e.key==='ArrowUp'?-.15:.15;wake();}});
 const resize=new ResizeObserver(draw);resize.observe(canvas);const stop=()=>{cancelAnimationFrame(frame);frame=0;grab=-1;previous=null;target=null;};const visibility=()=>{if(document.hidden)stop();else wake();};document.addEventListener('visibilitychange',visibility);
 m._resetSquishy=()=>{stop();yaw=.65;pitch=.35;accumulator=0;for(const n of nodes){n.p=[...n.r];n.old=[...n.r];}wake();notifyBoardChanged('squishy-reset')};
 m._boardGetState=()=>({version:2,yaw,pitch});m._boardSetState=s=>{yaw=Number.isFinite(s?.yaw)?s.yaw:.65;pitch=Number.isFinite(s?.pitch)?Math.max(-1.2,Math.min(1.2,s.pitch)):.35;wake();};const oldDeactivate=m._deactivate,oldCleanup=m._cleanup;m._deactivate=()=>{stop();oldDeactivate?.();};m._cleanup=()=>{disposed=true;stop();resize.disconnect();document.removeEventListener('visibilitychange',visibility);gl.deleteBuffer(buffer);gl.deleteProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);oldCleanup?.();};wake();
}
window.TeacherTilesSquishy3D={setup};})();
