(()=>{'use strict';
function sound(m){
 const audio=new Audio('assets/ui/squishy-press.wav');audio.preload='auto';
 const api=window.TeacherTilesTileAudio;
 const stop=()=>{audio.pause();audio.currentTime=0};
 const volume=()=>{const level=api?.level(m)??1;api?.mediaVolume(audio,level*.65);if(level<=0)stop();return level};
 m._playSquish=()=>{if(!m.isConnected||document.hidden||volume()<=0)return;audio.currentTime=0;audio.play().catch(()=>{})};
 const visibility=()=>{if(document.hidden)stop()};
 m.addEventListener('teachertiles:tileaudiochange',volume);document.addEventListener('visibilitychange',visibility);
 const deactivate=m._deactivate,cleanup=m._cleanup;
 m._deactivate=()=>{stop();deactivate?.()};
 m._cleanup=()=>{stop();api?.release(audio);audio.removeAttribute('src');audio.load();m._playSquish=()=>{};m.removeEventListener('teachertiles:tileaudiochange',volume);document.removeEventListener('visibilitychange',visibility);cleanup?.()};
}
function controls(m){
 sound(m);
 const colors={default:['Default',0,'#52d1d8'],ocean:['Ocean',30,'#63a2e6'],lavender:['Lavender',85,'#ad83de'],rose:['Rose',145,'#e585b3'],amber:['Amber',205,'#eab35e'],lime:['Lime',280,'#8fca78']};
 const bar=document.createElement('div');bar.className='squishy-controls';const toggle=document.createElement('button');toggle.type='button';toggle.className='squishy-color-toggle';toggle.setAttribute('aria-label','Squishy color');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<i></i><span aria-hidden="true">+</span>';bar.append(toggle);
 if(m._resetSquishy){const reset=document.createElement('button');reset.type='button';reset.textContent='Reset';reset.className='squishy-reset';reset.onclick=()=>m._resetSquishy();bar.append(reset);}m.append(bar);
 const drawer=document.createElement('div');drawer.className='squishy-color-drawer';drawer.setAttribute('popover','manual');drawer.setAttribute('role','group');drawer.setAttribute('aria-label','Squishy colors');m.append(drawer);
 const setColor=value=>{const key=colors[value]?value:'default';m.dataset.squishyColor=key;m.style.setProperty('--squishy-hue',colors[key][1]+'deg');toggle.style.setProperty('--swatch',colors[key][2]);drawer.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.color===key)));};
 const close=()=>{if(drawer.matches(':popover-open'))drawer.hidePopover();toggle.setAttribute('aria-expanded','false');};
 for(const [key,[label,hue,color]] of Object.entries(colors)){const button=document.createElement('button');button.type='button';button.dataset.color=key;button.innerHTML='<i style="background:'+color+'"></i><span>'+label+'</span>';button.onclick=()=>{setColor(key);close();notifyBoardChanged('squishy-color')};drawer.append(button);}
 toggle.onclick=()=>{if(drawer.matches(':popover-open')){close();return;}drawer.showPopover();const r=toggle.getBoundingClientRect();drawer.style.left=Math.max(8,Math.min(innerWidth-drawer.offsetWidth-8,r.left))+'px';drawer.style.top=Math.max(8,r.top-drawer.offsetHeight-8)+'px';toggle.setAttribute('aria-expanded','true');};
 const outside=e=>{if(!drawer.contains(e.target)&&!toggle.contains(e.target))close()};const keyboard=e=>{if(e.key==='Escape')close()};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',keyboard);
 const get=m._boardGetState,set=m._boardSetState,cleanup=m._cleanup,deactivate=m._deactivate;m._boardGetState=()=>({...get?.(),color:m.dataset.squishyColor});m._boardSetState=state=>{set?.(state);setColor(state?.color||m.dataset.squishyColor)};m._deactivate=()=>{close();deactivate?.()};m._cleanup=()=>{close();document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',keyboard);cleanup?.()};setColor(m.dataset.squishyColor);
}
function setup(m){
if(m.dataset.tileSkin==='squishy-gel-cube'){window.TeacherTilesSquishy3D.setup(m);controls(m);return;}

const canvas=m.querySelector('.squishy-canvas'),ctx=canvas.getContext('2d');let frame=0,held=false,disposed=false,last=0,pointer={x:160,y:170},origin={x:160,y:170},releaseTimer=0;const points=Array.from({length:48},(_,i)=>{const a=i/48*Math.PI*2,x=160+108*Math.sign(Math.cos(a))*Math.abs(Math.cos(a))**.4,y=171+95*Math.sign(Math.sin(a))*Math.abs(Math.sin(a))**.4;return {x,y,bx:x,by:y,vx:0,vy:0}});
function contour(){ctx.beginPath();const prev=points.at(-1),first=points[0];ctx.moveTo((prev.x+first.x)/2,(prev.y+first.y)/2);for(let i=0;i<points.length;i++){const p=points[i],next=points[(i+1)%points.length];ctx.quadraticCurveTo(p.x,p.y,(p.x+next.x)/2,(p.y+next.y)/2)}ctx.closePath()}
function draw(){ctx.clearRect(0,0,320,330);const spread=held?1.12:1;const shadow=ctx.createRadialGradient(163,279,4,163,279,110);shadow.addColorStop(0,'#1c688b22');shadow.addColorStop(1,'#1c688b00');ctx.fillStyle=shadow;ctx.save();ctx.translate(163,279);ctx.scale(spread,.18);ctx.beginPath();ctx.arc(0,0,110,0,Math.PI*2);ctx.restore();ctx.fill();
contour();ctx.save();ctx.clip();const gel=ctx.createLinearGradient(50,80,260,270);gel.addColorStop(0,'#00aac4');gel.addColorStop(.25,'#51d0dd');gel.addColorStop(.55,'#9ee3e8');gel.addColorStop(.82,'#00b8d2');gel.addColorStop(1,'#008bad');ctx.fillStyle=gel;ctx.fillRect(0,0,320,330);
const center=points.reduce((a,p)=>({x:a.x+p.x/points.length,y:a.y+p.y/points.length}),{x:0,y:0});const glow=ctx.createRadialGradient(center.x-19,center.y-37,10,center.x,center.y,121);glow.addColorStop(0,'#e5ffffbb');glow.addColorStop(.65,'#d1ffff35');glow.addColorStop(1,'#00a4c833');ctx.fillStyle=glow;ctx.fillRect(0,0,320,330);
ctx.strokeStyle='#d9ffff77';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(points[28].x+12,points[28].y+18);ctx.quadraticCurveTo(140+(center.x-160),90+(center.y-171),points[39].x-12,points[39].y+18);ctx.stroke();ctx.strokeStyle='#007fa522';ctx.lineWidth=17;ctx.beginPath();ctx.moveTo(points[2].x-15,points[2].y);ctx.quadraticCurveTo(265,250,points[11].x,points[11].y-9);ctx.stroke();const glint=ctx.createRadialGradient(center.x-38,center.y-47,0,center.x-38,center.y-47,22);glint.addColorStop(0,'#ffffffaa');glint.addColorStop(1,'#ffffff00');ctx.fillStyle=glint;ctx.fillRect(0,0,320,330);ctx.restore();contour();ctx.lineWidth=1.5;ctx.strokeStyle='#9ee8ef99';ctx.stroke()}
function tick(now){frame=0;if(disposed||!m.isConnected)return;const dt=Math.min(2,Math.max(.3,(now-last)/16.67||1));last=now;let energy=0;for(const p of points){const dx=p.bx-origin.x,dy=p.by-origin.y,weight=Math.exp(-(dx*dx+dy*dy)/18000);const tx=p.bx+(held?((p.bx-160)*.1+(pointer.x-origin.x)*weight*.65):0),ty=p.by+(held?(-(p.by-171)*.18+(pointer.y-origin.y)*weight*.65):0);p.vx=(p.vx+(tx-p.x)*.065*dt)*.78**dt;p.vy=(p.vy+(ty-p.y)*.065*dt)*.78**dt;p.x+=p.vx*dt;p.y+=p.vy*dt;energy+=Math.abs(p.vx)+Math.abs(p.vy)+Math.abs(tx-p.x)+Math.abs(ty-p.y)}draw();if(held||energy>.08)frame=requestAnimationFrame(tick);else{points.forEach(p=>{p.x=p.bx;p.y=p.by;p.vx=p.vy=0});draw()}}
const wake=()=>{if(!frame&&!disposed){last=performance.now();frame=requestAnimationFrame(tick)}};
const locate=e=>{const r=canvas.getBoundingClientRect(),scale=Math.min(r.width/320,r.height/330);return {x:Math.max(40,Math.min(280,(e.clientX-r.x-(r.width-320*scale)/2)/scale)),y:Math.max(50,Math.min(280,(e.clientY-r.y-(r.height-330*scale)/2)/scale))}};
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();canvas.setPointerCapture(e.pointerId);origin=pointer=locate(e);held=true;m._playSquish?.();wake()});canvas.addEventListener('pointermove',e=>{if(held){pointer=locate(e);wake()}});const release=()=>{held=false;wake()};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);canvas.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.repeat){e.preventDefault();held=true;m._playSquish?.();origin=pointer={x:160,y:170};wake();clearTimeout(releaseTimer);releaseTimer=setTimeout(release,250)}});
function rest(){held=false;cancelAnimationFrame(frame);frame=0;clearTimeout(releaseTimer);points.forEach(p=>{p.x=p.bx;p.y=p.by;p.vx=p.vy=0});draw()}
const skinObserver=new MutationObserver(()=>wake());skinObserver.observe(m,{attributes:true,attributeFilter:['data-tile-skin']});
const visibility=()=>{if(document.hidden)rest()};document.addEventListener('visibilitychange',visibility);const dpr=Math.min(devicePixelRatio||1,2);canvas.width=320*dpr;canvas.height=330*dpr;ctx.scale(dpr,dpr);m._boardGetState=()=>({version:1});m._boardSetState=rest;const deactivate=m._deactivate;m._deactivate=()=>{rest();deactivate?.()};const cleanup=m._cleanup;m._cleanup=()=>{disposed=true;skinObserver.disconnect();rest();document.removeEventListener('visibilitychange',visibility);cleanup?.()};draw();controls(m);
}window.TeacherTilesSquishy=Object.freeze({setup});})();
