(()=>{'use strict';
const presets=[['Line Leader','🚶'],['Door Holder','🚪'],['Light Monitor','💡'],['Paper Passer','📄'],['Librarian','📚'],['Plant Caretaker','🌱'],['Board Cleaner','🧽'],['Technology Helper','💻'],['Supply Manager','✏️'],['Calendar Helper','📅'],['Weather Reporter','🌤️'],['Class Messenger','✉️'],['Recycling Helper','♻️'],['Cleanup Captain','🧹'],['Lunch Helper','🍎'],['Attendance Helper','📋'],['Kindness Ambassador','💛'],['Pet Caretaker','🐠']];
const el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
const btn=(text,fn)=>{const b=el('button','',text);b.type='button';b.onclick=fn;return b;};
function setup(m){
 let jobs=[],classId='',assignments={},selected='',dragged='',editor=null;
 const grid=m.querySelector('.jobs-grid'),intro=m.querySelector('.jobs-intro'),label=m.querySelector('.jobs-class'),status=m.querySelector('.jobs-status');
 const add=m.querySelector('.jobs-add');add.classList.add('jobs-add-card');
 const roster=()=>readClassRosters().find(c=>c.id===classId);
 const names=()=>[...new Set(roster()?.students||[])];
 const save=()=>notifyBoardChanged('classroom-jobs');
 function reconcile(){if(!roster())return;const next=Object.assign(Object.create(null),assignments[classId]||{});for(const name of Object.keys(next))if(!jobs.some(j=>j.id===next[name]))delete next[name];assignments[classId]=next;}
 function move(name,id){if(!names().includes(name)||!jobs.some(j=>j.id===id))return;assignments[classId][name]=id;selected='';render();save();status.textContent=name+' moved to '+jobs.find(j=>j.id===id).title;}
 function render(){reconcile();const r=roster();intro.hidden=!!r;label.textContent=r?r.name:'No class selected';grid.replaceChildren();m.querySelectorAll('[data-jobs-action]').forEach(b=>b.disabled=!r||!names().length||!jobs.length);if(!r){grid.append(add);return;}
 for(const job of jobs){const card=el('section','jobs-card');card.dataset.job=job.id;const head=el('div','jobs-card-head'),art=el('span','jobs-art');if(job.image){const img=el('img');img.src=job.image;img.alt='';art.append(img);}else art.textContent=job.icon||'⭐';const target=btn(job.title,()=>{if(selected)move(selected,job.id);});target.className='jobs-target';target.title='Select a student, then click a job to move them';const edit=btn('⋯',()=>editJob(job));edit.className='jobs-edit';edit.setAttribute('aria-label','Edit '+job.title);head.append(art,target,edit);card.append(head);const remove=btn('×',()=>{jobs=jobs.filter(j=>j.id!==job.id);selected='';render();save();status.textContent=job.title+' removed';});remove.className='jobs-delete';remove.setAttribute('aria-label','Delete '+job.title);card.append(remove);
 const students=names().filter(n=>assignments[classId]?.[n]===job.id),assigned=el('div','jobs-assigned');card.append(assigned);for(const name of students){const chip=btn(name,()=>{selected=selected===name?'':name;render();status.textContent=selected?'Choose a job for '+selected:'';});chip.className='jobs-student';chip.draggable=true;chip.setAttribute('aria-pressed',String(selected===name));chip.ondragstart=e=>{dragged=name;e.dataTransfer.setData('text/plain',name);e.dataTransfer.effectAllowed='move';e.stopPropagation();};chip.ondragend=()=>{dragged='';grid.querySelectorAll('.is-drop-target').forEach(c=>c.classList.remove('is-drop-target'));};assigned.append(chip);}if(!students.length)assigned.append(el('span','jobs-vacancy','No student assigned'));
 const select=el('select','jobs-student-select');select.setAttribute('aria-label','Assign a student to '+job.title);select.append(new Option('Assign student…',''));for(const name of names()){if(students.includes(name))continue;const current=jobs.find(j=>j.id===assignments[classId]?.[name]);select.append(new Option(name+(current?' · '+current.title:''),name));}select.disabled=select.options.length===1;select.onchange=()=>{if(select.value)move(select.value,job.id);};select.addEventListener('pointerdown',e=>e.stopPropagation());card.append(select);
 card.ondragover=e=>{if(!dragged)return;e.preventDefault();e.stopPropagation();card.classList.add('is-drop-target');e.dataTransfer.dropEffect='move';};card.ondragleave=e=>{if(!card.contains(e.relatedTarget))card.classList.remove('is-drop-target');};card.ondrop=e=>{if(!dragged)return;e.preventDefault();e.stopPropagation();move(dragged,job.id);dragged='';};grid.append(card);}
 grid.append(add);
 }
 function rotate(shuffle){if(!roster()||!jobs.length)return;const list=names();if(shuffle){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}list.forEach((n,i)=>assignments[classId][n]=jobs[i%jobs.length].id);}else for(const n of list){const i=jobs.findIndex(j=>j.id===assignments[classId][n]);assignments[classId][n]=jobs[(i+1)%jobs.length].id;}selected='';render();save();status.textContent=shuffle?'Jobs shuffled':'Everyone moved one job forward';if(!matchMedia('(prefers-reduced-motion: reduce)').matches)grid.animate([{opacity:.45,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:240});}
 function editJob(job){if(editor)return;editor=el('dialog','jobs-editor');const d=editor,form=el('form'),title=el('input'),file=el('input'),notice=el('p'),heading=el('h2','',job?'Edit job':'Create a job');let image=job?.image||'',processing=false;title.value=job?.title||'';title.maxLength=60;title.required=true;file.type='file';file.accept='image/png,image/jpeg,image/webp';const tl=el('label','','Job title'),il=el('label','','Job image');tl.append(title);il.append(file);const preview=el('img','jobs-image-preview');preview.hidden=!image;preview.src=image;const submit=btn('Save job',()=>{});submit.type='submit';file.onchange=async()=>{const f=file.files[0];if(!f)return;if(f.size>8*1024*1024){notice.textContent='Choose an image under 8 MB.';return;}processing=true;submit.disabled=true;try{const bitmap=await createImageBitmap(f),canvas=document.createElement('canvas'),scale=Math.min(1,192/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();image=canvas.toDataURL('image/webp',.8);preview.src=image;preview.hidden=false;notice.textContent='';}catch{notice.textContent='That image could not be opened.';}finally{processing=false;submit.disabled=false;}};
 const actions=el('div','jobs-editor-actions');actions.append(btn('Cancel',()=>d.close()),submit);form.append(heading,tl,il,preview,btn('Remove image',()=>{image='';preview.hidden=true;file.value='';}),notice,actions);if(job){const remove=btn('Delete job',()=>{jobs=jobs.filter(j=>j.id!==job.id);render();save();d.close();});form.append(remove);}form.onsubmit=e=>{e.preventDefault();if(processing)return;const value=title.value.trim();if(!value){notice.textContent='Enter a job title.';return;}if(job){job.title=value;job.image=image;}else jobs.push({id:crypto.randomUUID(),title:value,icon:'⭐',image});render();save();d.close();};d.append(form);document.body.append(d);d.onclose=()=>{d.remove();editor=null;};d.showModal();title.focus();}
 const picker=el('div','jobs-picker');picker.hidden=true;picker.setAttribute('aria-label','Add classroom job');
 picker.append(el('strong','jobs-picker-title','Choose a classroom job'));const options=el('div','jobs-preset-grid');
 presets.forEach(([title,icon],i)=>{const choice=btn('',()=>{jobs.push({id:crypto.randomUUID(),title,icon,image:''});picker.hidden=true;add.setAttribute('aria-expanded','false');render();save();});choice.append(el('span','',icon),el('span','',title));options.append(choice);});picker.append(options,btn('+ Create your own',()=>{picker.hidden=true;editJob();}));m.append(picker);
 const closeControls=()=>{if(m.contains(document.activeElement)&&document.activeElement.matches('button'))document.activeElement.blur();picker.hidden=true;intro.hidden=!!roster();selected='';grid.querySelectorAll('[aria-pressed=true]').forEach(c=>c.setAttribute('aria-pressed','false'));add.setAttribute('aria-expanded','false');};m.addEventListener('pointerleave',closeControls);
 const detach=attachClassRosterLoader(m.querySelector('.jobs-loader'),(_,c)=>{classId=c.id;selected='';render();save();});
 m.querySelector('.jobs-change').onclick=()=>{intro.hidden=!intro.hidden;};add.onclick=()=>{picker.hidden=!picker.hidden;add.setAttribute('aria-expanded',String(!picker.hidden));};m.querySelector('.jobs-shuffle').onclick=()=>rotate(true);m.querySelector('.jobs-shift').onclick=()=>rotate(false);
 m.addEventListener('wheel',e=>e.stopPropagation(),{passive:true});m.querySelector('.jobs-grid').addEventListener('pointerdown',e=>e.stopPropagation());
 for(const [selector,key,values] of [['.tile-bg','bg',['white','cream','blue','pink','green','lavender','charcoal']],['.tile-font','font',FONT_OPTIONS],['.tile-text','text',['dark','soft','blue','rose','white','cream']]])m.querySelector(selector).onclick=()=>cycleData(m,key,values);
 createStandardTileSettingsPanel(m,'classroomjobs');
 m._boardGetState=()=>JSON.parse(JSON.stringify({version:1,classId,jobs,assignments}));
 m._boardSetState=s=>{if(Array.isArray(s?.jobs)){const seen=new Set();jobs=s.jobs.filter(j=>j&&typeof j.id==='string'&&!seen.has(j.id)&&seen.add(j.id)).slice(0,100).map(j=>({id:j.id,title:String(j.title||'Job').slice(0,60),icon:String(j.icon||'⭐').slice(0,12),image:/^data:image\/(png|jpeg|webp);base64,/.test(j.image||'')?j.image:''}));}classId=String(s?.classId||'');assignments=s?.assignments&&typeof s.assignments==='object'?JSON.parse(JSON.stringify(s.assignments)):{};selected='';render();};
 const onClasses=()=>{const before=JSON.stringify(assignments);render();if(before!==JSON.stringify(assignments))save();};window.addEventListener('teachertiles:classeschange',onClasses);const prior=m._cleanup;m._cleanup=()=>{detach();editor?.close();window.removeEventListener('teachertiles:classeschange',onClasses);prior?.();};const deactivate=m._deactivate;m._deactivate=()=>{editor?.close();deactivate?.();};render();
}
window.TeacherTilesClassroomJobs={setup};})();
