const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(__dirname,'../..');
const fixture=fs.mkdtempSync(path.join(os.tmpdir(),'tt-portal-test-'));fs.mkdirSync(path.join(fixture,'sandbox'));fs.copyFileSync(path.join(root,'index.html'),path.join(fixture,'index.html'));fs.copyFileSync(path.join(root,'sandbox/portal.html'),path.join(fixture,'sandbox/portal.html'));require('../build.cjs').buildSandbox(fixture);
const authMock=`export const browserLocalPersistence={};export const getAuth=()=>window.fakeAuth||(window.fakeAuth={currentUser:null});export const setPersistence=async()=>{};export class GoogleAuthProvider{setCustomParameters(){}}export const onIdTokenChanged=(auth,callback)=>{window.authCallback=callback;queueMicrotask(()=>callback(auth.currentUser));};export const signInWithPopup=async auth=>{auth.currentUser={uid:'admin-user',email:'admin@example.com',displayName:'Test Administrator',metadata:{creationTime:'2026-09-01'}};window.authCallback(auth.currentUser);return {user:auth.currentUser}};export const signOut=async auth=>{auth.currentUser=null;window.authCallback(null)};export const getIdTokenResult=async()=>({claims:{portalRole:window.testRole||'admin'}});`;
const functionsMock=`export const getFunctions=()=>({});export const httpsCallable=(_,name)=>async()=>{window.calls.push(name);if(window.testError)throw Object.assign(Error('verification failed'),{code:window.testError,details:{reason:'auth-reader-missing'}});if(name==='verifyDeveloperAccess'){if(window.testRole==='member')throw Object.assign(Error('denied'),{code:'functions/permission-denied'});return {data:{uid:'admin-user',role:window.testRole||'admin'}}}return {data:{coinBalance:0,ownedProductIds:[],subscriptionActive:false}}};`;
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.calls=[];window.Audio=class extends EventTarget{constructor(src){super();this.src=src;this.volume=1}play(){return Promise.resolve()}pause(){}load(){}removeAttribute(){}cloneNode(){return new Audio(this.src)}}});
await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname==='www.gstatic.com'){
 let body;if(url.pathname.endsWith('firebase-app.js'))body='export const initializeApp=()=>({});';else if(url.pathname.endsWith('firebase-auth.js'))body=authMock;else if(url.pathname.endsWith('firebase-functions.js'))body=functionsMock;else if(url.pathname.endsWith('firebase-firestore.js'))body='export const getFirestore=()=>({});';return body?route.fulfill({contentType:'application/javascript',body}):route.abort();}
if(url.hostname!=='tiles.test')return route.abort();let file;if(url.pathname==='/sandbox/')file=path.join(fixture,'index.html');else if(url.pathname==='/sandbox/board.html')file=path.join(fixture,'board.html');else file=path.join(root,decodeURIComponent(url.pathname.replace(/^\/sandbox\//,'/').replace(/^\/$/,'/index.html')));return fs.existsSync(file)&&fs.statSync(file).isFile()?route.fulfill({path:file}):route.abort();});
await page.goto('http://tiles.test/sandbox/');await page.getByRole('button',{name:'Sign in with Google'}).waitFor();await page.getByRole('button',{name:'Sign in with Google'}).click();await page.locator('#portal-home').waitFor({state:'visible'});assert.equal(await page.locator('#workspace').count(),0);assert.deepEqual(await page.evaluate(()=>calls),['verifyDeveloperAccess']);assert.equal(await page.locator('#enter-board-sandbox').getAttribute('href'),'board.html');await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/developer-portal.png'});
await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.locator('#portal-login').waitFor({state:'visible'});await page.evaluate(()=>testRole='member');await page.getByRole('button',{name:'Sign in with Google'}).click();await page.waitForFunction(()=>document.getElementById('portal-status').textContent.includes('not an administrator'));assert.equal(await page.locator('#portal-home').isVisible(),false);
await page.evaluate(()=>{testRole='admin';testError='functions/failed-precondition'});await page.getByRole('button',{name:'Check access again'}).click();await page.waitForFunction(()=>document.getElementById('portal-status').textContent.includes('read permission'));assert.equal(await page.locator('#portal-home').isVisible(),false);
await page.evaluate(()=>testError=null);await page.getByRole('button',{name:'Check access again'}).click();await page.locator('#portal-home').waitFor({state:'visible'});
await page.locator('#enter-board-sandbox').click();await page.locator('#sandbox-access-gate').waitFor({state:'visible'});assert(await page.locator('#workspace').evaluate(e=>e.inert||!!e.closest('[inert]')));assert.equal(await page.locator('#sandbox-dev-console-toggle').count(),0);
assert.equal(await page.evaluate(()=>calls.length),0);
await page.locator('#sandbox-access-gate [data-signin]').click();await page.locator('#sandbox-access-gate').waitFor({state:'hidden'});await page.locator('#sandbox-dev-console-toggle').waitFor({state:'attached'});assert.equal(await page.locator('.sandbox-portal-return').getAttribute('href'),'./');
await page.goto('http://tiles.test/');assert.equal(await page.locator('#sandbox-access-gate').count(),0);assert.equal(await page.locator('#sandbox-dev-console-toggle').count(),0);assert.deepEqual(errors,[]);console.log('PASS: portal landing, verified access, roles, explicit server errors, retry, logout, board navigation and direct-board guard');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
