export const tileLabels={
  "classroomjobs": "Classroom Jobs",
  "chime": "Chime",
  "transitionbell": "Transition Bell",
  "sticky": "Sticky note",
  "richtext": "Rich Text",
  "piano": "Piano",
  "musicscore": "Music Score",
  "rainbow": "Rainbow",
  "colorpicker": "Color Picker",
  "visualdirections": "Visual Directions",
  "timer": "Timer",
  "wordoftheday": "Word of the Day",
  "quoteoftheday": "Quote of the Day",
  "vocabulary": "Vocabulary",
  "essentialquestion": "Essential Question",
  "wordweb": "Word Web",
  "venndiagram": "Venn Diagrams",
  "timestables": "Times Tables",
  "google": "Google",
  "link": "Link",
  "dice": "Dice",
  "randomnumber": "Random Number",
  "seatingchart": "Seating Chart",
  "fishtank": "Fish Tank",
  "spreadsheet": "Spreadsheet",
  "reminders": "Reminders",
  "sentenceexpansion": "Sentence Expansion",
  "coinflip": "Coin Flip",
  "squishy": "Squishy",
  "glitterjar": "Glitter Jar",
  "meditation": "Meditation",
  "rainbowbreath": "Rainbow Breath",
  "sleepymonster": "Sleepy Monster",
  "quietcritters": "Quiet Critters",
  "butterflygarden": "Butterfly Garden",
  "interactive": "Interactive timer",
  "clock": "Clock",
  "writinglines": "Writing lines",
  "stopwatch": "Stopwatch",
  "draw": "Drawing tools",
  "magnifier": "Magnifier",
  "noise": "Noise Meter",
  "collections": "Collection jar",
  "stoplight": "Stoplight",
  "starchart": "Star chart",
  "classmeter": "Class Meter",
  "prizeboard": "Prize Board",
  "pbisconsole": "PBIS Console",
  "egghatching": "Egg Hatching",
  "flowerpots": "Flower Pots",
  "punchcards": "Punchcards",
  "racer": "Racer",
  "classvsclass": "Class vs Class",
  "groupmaker": "Group maker",
  "lunchcount": "Lunch count",
  "voting": "Voting tile",
  "imagesearch": "Image Search",
  "image": "Image",
  "youtube": "YouTube module",
  "ambiencevideo": "Ambience video",
  "textbubble": "Text bubble",
  "todo": "Checklist",
  "date": "Date",
  "calendar": "Calendar",
  "lessonplannertile": "Lesson planner",
  "progressbar": "Progress bar",
  "popsiclesticks": "Popsicle Sticks",
  "visualschedule": "Visual schedule",
  "numberflashcards": "Number Flashcards tile",
  "windowshare": "Window Share",
  "boombox": "Soundscapes",
  "ruler": "Ruler",
  "calculator": "Calculator",
  "grapher": "Graphing tool",
  "periodictable": "Periodic table",
  "money": "Money tool",
  "attendance": "Attendance tile",
  "tablemaker": "Table Maker tile",
  "tallychart": "Tally Chart tile",
  "patternmaker": "Pattern maker",
  "shapemanipulatives": "Shape manipulatives",
  "cvcword": "CVC word tile",
  "highfrequency": "High Frequency Words tile",
  "robothfw": "Robot HFW tile",
  "customflashcards": "Custom Flashcards tile",
  "abc": "ABC tile",
  "numberline": "Number line",
  "hundredschart": "Hundreds chart",
  "tenframes": "Ten frames",
  "dictionary": "Dictionary",
  "translation": "Translation tile",
  "livecaption": "Live caption tile",
  "voicememo": "Voice memo tile",
  "photobooth": "Photobooth tile",
  "backgroundremover": "Background remover tile",
  "mirror": "Mirror tile",
  "weather": "Weather tile",
  "weatherwheel": "Weather wheel",
  "seasonwheel": "Season wheel",
  "temperature": "Temperature tile",
  "worldmap": "World map tile",
  "usstates": "US states map tile",
  "compass": "Compass tile",
  "shapes": "Shapes tile",
  "flyswat": "Fly Swat",
  "minesweeper": "Minesweeper",
  "hangman": "Hangman",
  "wordypuzzle": "Wordy Puzzle",
  "spinner": "Spinner",
  "sticker": "Sticker"
};
