const vm=require('vm'),fs=require('fs'),assert=require('assert/strict'),{webcrypto}=require('crypto');
const source=fs.readFileSync('account/collection-preferences.js','utf8'),cloud=new Map();let reads=0,writes=0;
const sdk={doc:(_,...parts)=>parts.join('/'),getDoc:async ref=>{reads++;return {exists:()=>cloud.has(ref),data:()=>structuredClone(cloud.get(ref))}},runTransaction:async(_,fn)=>fn({get:sdk.getDoc,set:(ref,data)=>{writes++;cloud.set(ref,structuredClone(data))}})};
function browser(initial={}){const data=new Map(Object.entries(initial));const window=new EventTarget(),document=new EventTarget();let timer;const ctx={window,document,localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},StorageEvent:class extends Event{constructor(t,p){super(t);Object.assign(this,p)}},Event,console,crypto:webcrypto,setTimeout:fn=>{timer=fn;return 1},clearTimeout:()=>{},Date};vm.runInNewContext(source,ctx);return {api:window.TeacherTilesCollectionPreferences,data,window};}
const wait=()=>new Promise(r=>setImmediate(r));const fav='teachertiles.sticker-favorites.v1',usage='teachertiles.sticker-usage.v1';
(async()=>{const a=browser({[fav]:'["cat"]',[usage]:'{"cat":4}'});a.api.setUser('one',sdk,{});await wait();await a.api.flush();const b=browser();b.api.setUser('one',sdk,{});await wait();assert.equal(b.data.get(fav),'["cat"]');assert.equal(JSON.parse(b.data.get(usage)).cat,4);
a.api.write(fav,'[]');b.api.write('teacherTilesCursorFavorites','["pixel"]');a.api.write(usage,'{"cat":5}');b.api.write(usage,'{"cat":5}');await a.api.flush();await b.api.flush();assert.equal(cloud.get('users/one/private/collectionPreferences').usage.cat,6);assert.equal(cloud.get('users/one/private/collectionPreferences').stickers.cat,false);
const c=browser({[fav]:'["cat"]',[usage]:'{"cat":4}'});c.api.setUser('one',sdk,{});await wait();await c.api.flush();assert.equal(c.data.get(fav),'[]','legacy cannot resurrect removed favorites');assert.equal(JSON.parse(c.data.get(usage)).cat,6,'legacy counts not duplicated');
a.api.setUser('two',sdk,{});await wait();assert.equal(a.data.get(fav),'[]');assert.equal(a.data.get('teacherTilesCursorFavorites'),'[]');a.api.setUser('one',sdk,{});await wait();assert.equal(a.data.get('teacherTilesCursorFavorites'),'["pixel"]');
const original=sdk.runTransaction;let failed=true;
sdk.runTransaction=async(db,fn)=>{const result=await original(db,fn);if(failed){failed=false;throw Error('Simulated lost acknowledgement')}return result};
a.api.write(usage,'{"cat":7}');await a.api.flush();await a.api.flush();assert.equal(cloud.get('users/one/private/collectionPreferences').usage.cat,7,'retry cannot double-count');sdk.runTransaction=original;
const before=writes;await a.api.flush();await a.api.flush();assert.equal(writes,before,'no writes when unchanged');console.log('Passed account isolation, cross-browser favorites, merged usage, stale legacy migration, and no-op write checks. Reads:',reads,'writes:',writes);
})().catch(e=>{console.error(e);process.exit(1)});
