const fs=require('fs'),path=require('path'),assert=require('assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{if(r.request().url().includes('sandbox/board-gate.js'))return r.abort();const u=new URL(r.request().url()),f=path.join(path.resolve(__dirname,'..'),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});await page.goto('http://tiles.test/');await page.evaluate(()=>{document.documentElement.classList.remove('sandbox-access-locked');for(const child of document.body.children)child.style.setProperty('visibility','hidden','important');window.sounds=[];window.TeacherTilesInstrument=()=>({note:async(...args)=>sounds.push(args),stop(){},close(){}});window.score=createModule('musicscore',300,200,{record:false});document.body.append(score);score.style.cssText+=';position:fixed!important;left:100px!important;top:100px!important;visibility:visible!important;z-index:2147483647!important;opacity:1!important;transform:none!important';});await page.locator('.music-staff').hover();await page.waitForTimeout(350);assert.equal(await page.locator('.score-duration').count(),6);
const state=()=>page.evaluate(()=>score._boardGetState());async function tool(d,rest=false){await page.locator(`.score-duration[data-duration="${d}"][data-rest="${rest}"]`).click();await page.waitForTimeout(180)}async function point(beat,pitchIndex=6){const r=await page.locator('.music-staff').boundingBox();return{x:r.x+(166+beat*52)/1000*r.width,y:r.y+(120-pitchIndex*10)/140*r.height}}async function place(beat,pi=6){const p=await point(beat,pi);await page.mouse.click(p.x,p.y)}
await tool(1);await place(0);await tool(2);await place(2,5);await tool(4);await place(4,7);assert.deepEqual((await state()).notes.map(n=>n.duration),[1,2,4]);await tool(1,true);await place(1);await tool(2,true);await place(8);await tool(4,true);await place(12);assert.equal((await state()).notes.filter(n=>n.rest).length,3);
await page.locator('.music-staff-note[data-note="0"]').click();assert((await state()).notes[0].rest);await page.locator('.music-staff-note[data-note="0"]').click();assert.equal((await state()).notes[0].rest,false);
const count=(await state()).notes.length,rect=await page.locator('.music-staff').boundingBox();for(const xy of [[.5,.02],[.5,.98],[.06,.55]])await page.mouse.click(rect.x+rect.width*xy[0],rect.y+rect.height*xy[1]);assert.equal((await state()).notes.length,count,'padding/clef cannot accept notes');
const saved=await page.evaluate(()=>serializeBoardModule(score));await page.evaluate(s=>{score._cleanup();score.remove();window.score=restoreTeacherTilesBoardObject(s);document.body.append(score);score.style.cssText+=';position:fixed!important;left:100px!important;top:100px!important;visibility:visible!important;z-index:2147483647!important;opacity:1!important;transform:none!important';},saved);assert.deepEqual((await state()).notes,saved.special.notes);
await page.locator('.music-staff').hover();await page.waitForTimeout(300);await page.locator('.score-tempo').fill('120');await page.locator('.score-tempo').dispatchEvent('change');await page.evaluate(()=>sounds=[]);await page.locator('.score-play').click();const sounds=await page.evaluate(()=>sounds);assert.equal(sounds.length,3);assert.deepEqual(sounds.map(n=>n[1]),[.45,.9,1.8]);assert.deepEqual(sounds.map(n=>n[2]),[0,1,2]);await page.locator('.score-stop').click();
await page.locator('.score-clear').click();await tool(2);const from=await page.locator('.score-duration[data-duration="2"][data-rest="false"]').boundingBox(),to=await point(7,4);await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:20});assert(await page.locator('.score-drop-note').isVisible());await page.mouse.up();await page.waitForTimeout(180);assert.equal((await state()).notes[0].beat,6);assert.equal((await state()).notes[0].duration,2);assert.equal(await page.locator('.score-drop-note').count(),0);
await tool(4);await place(5);assert.equal((await state()).notes.length,1,'overlapping beats replaced');assert.equal((await state()).notes[0].beat,4);assert.equal((await state()).notes[0].duration,4);
await page.evaluate(()=>score._boardSetState({notes:[60,{beat:4,pitch:84,rest:true}],tempo:100}));assert.deepEqual((await state()).notes.map(n=>n.duration),[1,1]);assert((await state()).notes[1].rest);await page.mouse.move(1050,700);await page.waitForTimeout(300);assert.equal(await page.locator('.score-toolbar-slot').evaluate(el=>getComputedStyle(el).visibility),'hidden');await page.evaluate(()=>{score.style.width='360px';score.style.height='360px'});await page.locator('.music-staff').hover();await page.waitForTimeout(300);assert(await page.locator('.music-staff').evaluate(el=>el.clientHeight>70));assert(await page.locator('.score-toolbar').evaluate(el=>el.scrollWidth<=el.clientWidth));assert.deepEqual(errors,[]);console.log('Passed six tools, placement bounds, note/rest toggles, duration restore, playback lengths, silent rests, palette dragging, measure alignment, overlap replacement, legacy scores and unhover.');}finally{await browser.close()}})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
