const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('tiles/spreadsheet/index.js','utf8'),sandbox);const calc=sandbox.window.TeacherTilesSpreadsheet.calculate;
assert.equal(calc({A1:'2',A2:'3',B1:'=SUM(A1:A2)*2'},'B1'),10);assert.equal(calc({A1:'=AVERAGE(B1:B2)',B1:'4',B2:'8'},'A1'),6);assert.throws(()=>calc({A1:'=B1',B1:'=A1'},'A1'),/#CYCLE/);assert.throws(()=>calc({A1:'=1/0'},'A1'),/#DIV/);assert.throws(()=>calc({A1:'=alert(1)'},'A1'),/#FORMULA/);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--unsafely-treat-insecure-origin-as-secure=http://tiles.test']});try{
const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('teacherTilesSandboxCoinsEnabled','true');window.Audio=class extends EventTarget{constructor(src){super();Object.assign(this,{src,paused:true,volume:1,currentTime:0,duration:20})}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}load(){}removeAttribute(){}cloneNode(){return new Audio(this.src)}};window.notices=[];window.Notification=class{static permission='granted';constructor(title,options){notices.push({title,...options})}}});
await page.route('**/*',r=>{const u=new URL(r.request().url()),f=path.join(process.cwd(),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});
await page.goto('http://tiles.test/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(1800);
await page.evaluate(()=>{document.getElementById('profile-modal').hidden=true;boardCamera.x=0;boardCamera.y=0;boardCamera.scale=1;applyBoardCamera();createModule('spreadsheet',500,100);createModule('reminders',1050,100)});

const sheet=page.locator('.spreadsheet-module');
await sheet.locator('[data-cell=A1]').fill('7');await sheet.locator('[data-cell=B1]').fill('=A1*2');await sheet.locator('[data-cell=A1]').click({button:'right'});assert(await page.locator('.sheet-context-menu').isVisible());assert.equal(await page.locator('#context-menu').isVisible(),false);await page.getByRole('menuitem',{name:'Insert row above',exact:true}).click();assert.equal(await sheet.evaluate(el=>el._boardGetState().cells.B2),'=A2*2');
await sheet.locator('[data-cell=A1]').click({button:'right'});await page.getByRole('menuitem',{name:'Delete row',exact:true}).click();assert.equal(await sheet.evaluate(el=>el._boardGetState().cells.B1),'=A1*2');
await sheet.locator('[data-cell=A1]').click({button:'right'});await page.getByRole('menuitem',{name:'Insert column left',exact:true}).click();assert.equal(await sheet.evaluate(el=>el._boardGetState().cells.C1),'=B1*2');
for(const axis of ['column','row']){const handle=sheet.locator('.sheet-resizer--'+axis).first(),r=await handle.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+(axis==='column'?55:0),r.y+r.height/2+(axis==='row'?25:0),{steps:8});await page.mouse.up()}
let state=await sheet.evaluate(el=>el._boardGetState());assert(state.columnWidths[0]>140);assert(state.rowHeights[0]>45);await page.evaluate(()=>TeacherTilesBoard.load(TeacherTilesBoard.capture()));assert.deepEqual(await sheet.evaluate(el=>el._boardGetState()),state);
for(const pinned of [false,true]){await sheet.evaluate((el,pinned)=>setTilePinned(el,pinned),pinned);const before=await sheet.evaluate(el=>captureModuleTransform(el));await sheet.locator('.module-fullscreen').evaluate(el=>el.click());await page.waitForFunction(()=>!!document.fullscreenElement);assert.deepEqual(await sheet.evaluate(el=>captureModuleTransform(el)),before);await page.evaluate(()=>window.dispatchEvent(new Event('resize')));await page.evaluate(()=>document.exitFullscreen());await page.waitForTimeout(300);assert.deepEqual(await sheet.evaluate(el=>captureModuleTransform(el)),before);assert.equal(await sheet.evaluate(el=>!!el._tileFullscreenGeometry),false)}
await page.locator('.reminders-add').click();assert(await page.locator('.reminders-form').isVisible());await page.waitForTimeout(300);await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/reminder-composer-refined.png'});await page.evaluate(()=>TeacherTilesBoard.load(TeacherTilesBoard.capture()));assert.equal(await page.locator('.reminders-form').isVisible(),false);assert.equal(await page.locator('.reminders-module').evaluate(el=>el.classList.contains('is-composing-reminder')),false);await page.locator('.reminders-add').click();await page.locator('.reminders-cancel').click();assert.equal(await page.locator('.reminders-form').isVisible(),false);
await page.locator('#theme-shelf-toggle').evaluate(el=>el.click());await page.waitForTimeout(400);await page.locator('.theme-picker-pack-heading').filter({hasText:'Default'}).first().click();assert(await page.locator('.theme-pack-fan').isVisible());await page.waitForTimeout(700);await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/theme-fan-refined.png'});await page.locator('.theme-pack-fan [data-theme-choice=dark]').click();assert.equal(await page.evaluate(()=>document.body.dataset.theme),'dark');await page.locator('#asset-shelf-close').click();await page.waitForTimeout(300);assert.equal(await page.locator('.theme-pack-fan').isVisible(),false);
assert.deepEqual(errors,[]);console.log('Spreadsheet structure/formula shifts, cell resizing/persistence, real fullscreen round trips (pinned and unpinned), reminder composer and theme fan passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});

