const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('tiles/spreadsheet/index.js','utf8'),sandbox);const calc=sandbox.window.TeacherTilesSpreadsheet.calculate;
assert.equal(calc({A1:'2',A2:'3',B1:'=SUM(A1:A2)*2'},'B1'),10);assert.equal(calc({A1:'=AVERAGE(B1:B2)',B1:'4',B2:'8'},'A1'),6);assert.throws(()=>calc({A1:'=B1',B1:'=A1'},'A1'),/#CYCLE/);assert.throws(()=>calc({A1:'=1/0'},'A1'),/#DIV/);assert.throws(()=>calc({A1:'=alert(1)'},'A1'),/#FORMULA/);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--unsafely-treat-insecure-origin-as-secure=http://tiles.test']});try{
const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('teacherTilesSandboxCoinsEnabled','true');window.Audio=class extends EventTarget{constructor(src){super();Object.assign(this,{src,paused:true,volume:1,currentTime:0,duration:20})}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}load(){}removeAttribute(){}cloneNode(){return new Audio(this.src)}};window.notices=[];window.Notification=class{static permission='granted';constructor(title,options){notices.push({title,...options})}}});
await page.route('**/*',r=>{const u=new URL(r.request().url()),f=path.join(process.cwd(),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});
await page.goto('http://tiles.test/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(1800);

await page.evaluate(()=>{document.getElementById('profile-modal').hidden=true;boardCamera.x=0;boardCamera.y=0;boardCamera.scale=1;applyBoardCamera();const sheet=createModule('spreadsheet',400,350);sheet.style.left='80px';sheet.style.top='150px';sheet.style.width='760px';const noise=createModule('noise',1100,350);noise.style.left='920px';noise.style.top='150px'});
const sheet=page.locator('.spreadsheet-module'),noise=page.locator('.noise-modern');await sheet.hover();await sheet.locator('[data-cell=A1]').fill('Hello');await sheet.locator('[data-cell=A2]').fill('world');await sheet.locator('[data-cell=A1]').click();await sheet.getByRole('button',{name:'Bold',exact:true}).click();assert.equal(await sheet.locator('[data-cell=A1]').evaluate(el=>getComputedStyle(el).fontWeight),'700');await sheet.getByLabel('Cell font size',{exact:true}).selectOption('22');assert.equal(await sheet.locator('[data-cell=A1]').evaluate(el=>getComputedStyle(el).fontSize),'22px');
await sheet.locator('[data-cell=A1]').click();await sheet.locator('[data-cell=A2]').click({modifiers:['Shift']});assert.equal(await sheet.locator('.is-selected').count(),2);await sheet.getByRole('button',{name:'Italic',exact:true}).click();assert.equal(await sheet.locator('[data-cell=A2]').evaluate(el=>getComputedStyle(el).fontStyle),'italic');await sheet.getByLabel('Cell highlight color').fill('#ffccaa');assert.equal(await sheet.locator('[data-cell=A1]').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 204, 170)');await sheet.getByRole('button',{name:'Align right',exact:true}).click();assert.equal(await sheet.locator('[data-cell=A2]').evaluate(el=>getComputedStyle(el).textAlign),'right');
await sheet.locator('[data-cell=A2]').focus();await page.keyboard.press('Control+z');assert.equal(await sheet.locator('[data-cell=A2]').evaluate(el=>getComputedStyle(el).textAlign),'left');await page.keyboard.press('Control+y');await page.keyboard.press('Control+z');await page.keyboard.press('Control+Shift+z');assert.equal(await sheet.locator('[data-cell=A2]').evaluate(el=>getComputedStyle(el).textAlign),'right');
await sheet.locator('[data-cell=C1]').fill('1');await sheet.locator('[data-cell=C2]').fill('2');await sheet.locator('[data-cell=C3]').fill('=SUM(C1:C2)');await sheet.locator('[data-cell=C3]').blur();assert.equal(await sheet.locator('[data-cell=C3]').inputValue(),'3');
const saved=await sheet.evaluate(el=>el._boardGetState());await page.evaluate(()=>TeacherTilesBoard.load(TeacherTilesBoard.capture()));assert.deepEqual(await sheet.evaluate(el=>el._boardGetState()),saved);await sheet.hover();await sheet.locator('[data-cell=A1]').click();await sheet.getByRole('button',{name:'Bulleted list',exact:true}).click();assert.equal(await sheet.evaluate(el=>el._boardGetState().cells.A1),'• Hello');
await sheet.locator('[data-cell=B1]').click();await sheet.locator('input[type=file]').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=8;c.getContext('2d').fillRect(0,0,8,8);return c.toDataURL('image/png').split(',')[1]}),'base64')});await page.waitForTimeout(400);assert.equal(await sheet.locator('.sheet-cell-image').count(),1);await sheet.locator('.sheet-cell-image').click();await page.keyboard.press('Delete');assert.equal(await sheet.locator('.sheet-cell-image').count(),0);await page.keyboard.press('Control+z');assert.equal(await sheet.locator('.sheet-cell-image').count(),1);assert.equal(await sheet.getByRole('button',{name:'Wrap cell text'}).count(),0);await sheet.locator('[data-cell=D1]').fill('This long cell text should wrap automatically across several lines');assert.equal(await sheet.locator('[data-cell=D1]').evaluate(el=>getComputedStyle(el).whiteSpace),'pre-wrap');assert((await sheet.locator('[data-cell=D1]').boundingBox()).height>40);
await noise.hover();await noise.getByRole('button',{name:'Choose noise display'}).click();assert(await page.locator('.nm-drawer').isVisible());await page.locator('.nm-drawer').getByRole('button',{name:'Rising bars'}).click();assert.equal(await noise.getAttribute('data-noise-view'),'vertical');const line=await noise.evaluate(m=>{const ctx=m.querySelector('canvas').getContext('2d'),points=[],move=ctx.moveTo.bind(ctx),to=ctx.lineTo.bind(ctx);ctx.moveTo=(x,y)=>{points.push([x,y]);move(x,y)};ctx.lineTo=(x,y)=>{points.push([x,y]);to(x,y)};m.querySelector('.noise-range').dispatchEvent(new Event('input'));ctx.moveTo=move;ctx.lineTo=to;return points.slice(-2)});assert.equal(line.length,2);assert.equal(line[0][1],line[1][1]);assert.notEqual(line[0][0],line[1][0]);
await noise.hover();await page.waitForTimeout(300);await noise.getByRole('button',{name:'Choose noise color'}).click();await page.locator('.nm-drawer').getByRole('button',{name:'Lavender'}).click();assert.equal(await noise.getAttribute('data-meter'),'purple');assert.equal(await noise.locator('.noise-view-select').isVisible(),false);assert.equal(await noise.locator('.nm-color').isVisible(),false);
await page.evaluate(()=>{document.body.classList.add('is-keyboard-navigation');document.querySelector('.noise-start').focus();boardCamera.scale=.7;applyBoardCamera()});await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>document.activeElement===document.body),true);assert.equal(await page.evaluate(()=>document.body.classList.contains('is-keyboard-navigation')),false);assert.equal(await page.evaluate(()=>boardCamera.scale),1);await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement===document.body),true);
await page.evaluate(()=>{boardCamera.x=0;boardCamera.y=0;boardCamera.scale=1;applyBoardCamera()});await page.waitForTimeout(500);await sheet.hover();await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/sheet-format-noise.png'});
await noise.hover();await noise.getByRole('button',{name:'Choose noise display'}).click();await page.locator('.nm-drawer').getByRole('button',{name:'Single bar',exact:true}).click();assert.equal(await noise.getAttribute('data-noise-view'),'single');assert((await noise.boundingBox()).height>(await noise.boundingBox()).width);await page.mouse.move(1450,950);await page.waitForTimeout(300);assert.equal(await noise.locator('.nm-drawer-controls').evaluate(el=>getComputedStyle(el).opacity),'0');await page.evaluate(()=>{boardCamera.x=0;boardCamera.y=0;boardCamera.scale=1;applyBoardCamera();const m=document.querySelector('.noise-modern');m.style.left='920px';m.style.top='150px'});await page.waitForTimeout(400);await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/single-noise-meter.png'});const meterState=await noise.evaluate(el=>el._boardGetState());await page.evaluate(()=>TeacherTilesBoard.load(TeacherTilesBoard.capture()));assert.deepEqual(await noise.evaluate(el=>el._boardGetState()),meterState);assert.deepEqual(errors,[]);console.log('Cell/range formatting, undo/redo, formulas, image insertion, save/restore, noise drawers/horizontal threshold, Space focus removal and Tab navigation passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
