const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Jack/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1200,height:850}});await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='tiles.test')return r.abort();if(u.pathname==='/')return r.fulfill({contentType:'text/html',body:'<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/templates/style.css"><div id="host" hidden style="width:500px;height:300px"></div>'});const p=path.join(process.cwd(),u.pathname);return fs.existsSync(p)?r.fulfill({path:p}):r.abort();});await page.goto('http://tiles.test/');
 await page.evaluate(async html=>{const doc=new DOMParser().parseFromString(html,'text/html');document.body.append(doc.getElementById('sticky-template').cloneNode(true));const {createBoardPreview}=await import('/boards/preview.js');document.getElementById('host').append(createBoardPreview({inlineObjects:[{type:'sticky',transform:{width:300,height:220},editables:[{html:'All of this content must fit.'}]}]}));},fs.readFileSync('index.html','utf8'));await page.waitForTimeout(80);await page.locator('#host').evaluate(n=>n.hidden=false);await page.waitForFunction(()=>{const m=document.querySelector('.is-real-tile>.module');return getComputedStyle(m).visibility==='visible'&&getComputedStyle(m).transform!=='none';});const dimensions=await page.locator('.is-real-tile').evaluate(n=>{const a=n.getBoundingClientRect(),b=n.querySelector('.module').getBoundingClientRect();return {parent:a.width,child:b.width};});assert(dimensions.child<=dimensions.parent+1);await page.locator('#host').evaluate(n=>n.style.width='250px');await page.waitForTimeout(80);assert(await page.locator('.is-real-tile').evaluate(n=>n.querySelector('.module').getBoundingClientRect().width<=n.getBoundingClientRect().width+1));
 await page.evaluate(async()=>{window.access=await import('/boards/access.js');window.choice=access.cosmeticAccessDialog({importing:true});});await page.getByRole('heading',{name:"A few cosmetics are missing"}).waitFor();await page.getByRole('button',{name:'Back'}).click();assert.equal(await page.evaluate(()=>choice),'back');
 await page.evaluate(()=>{window.choice=access.cosmeticAccessDialog();});await page.getByRole('button',{name:'Remove unowned paid items'}).click();assert.equal(await page.evaluate(()=>choice),'remove');
 await page.unroute('**/*');await page.route('**/*',r=>{const u=new URL(r.request().url()),f=path.join(process.cwd(),u.pathname==='/'?'index.html':u.pathname);return u.hostname==='tiles.test'&&fs.existsSync(f)?r.fulfill({path:f}):r.abort();});await page.goto('http://tiles.test/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.TeacherTilesShop?.openMembership);await page.evaluate(async()=>{document.getElementById('teachertiles-intro')?.remove();document.body.classList.add('boards-screen-open');document.getElementById('boards-view').hidden=false;const api=await import('/boards/access.js');api.cosmeticAccessDialog({importing:true}).then(api.openCosmeticShop);});assert(await page.locator('.board-access-crown svg').isVisible());assert(await page.locator('.board-access-dialog').evaluate(e=>e.getBoundingClientRect().width<=410));await page.getByRole('button',{name:'Subscribe',exact:true}).click();await page.locator('#shop-subscribe-preview').waitFor({state:'visible'});await page.waitForTimeout(500);assert(await page.locator('#shop-subscribe-preview').evaluate(e=>{const b=e.getBoundingClientRect();return e.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2));}));
 console.log('PASS: hidden and resized previews fit; import and existing-board access dialogs work');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
