const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--unsafely-treat-insecure-origin-as-secure=http://tiles.test']});try{
const baseline=process.env.PERF_BASELINE==='1',old=baseline?Object.fromEntries(['app.js','tiles/shared/tabs.js'].map(file=>[file,require('child_process').execFileSync('git',['show','HEAD:'+file],{encoding:'utf8'})])):{};
const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('teacherTilesSandboxCoinsEnabled','true');window.Audio=class extends EventTarget{constructor(src){super();Object.assign(this,{src,paused:true,volume:1,currentTime:0,duration:20})}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}load(){}removeAttribute(){}cloneNode(){return new Audio(this.src)}};window.notices=[];window.Notification=class{static permission='granted';constructor(title,options){notices.push({title,...options})}}});
await page.route('**/*',r=>{const u=new URL(r.request().url()),f=path.join(process.cwd(),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(old[u.pathname.slice(1)])return r.fulfill({body:old[u.pathname.slice(1)],contentType:'application/javascript'});return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});
await page.goto('http://tiles.test/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(1800);



await page.evaluate(()=>{document.getElementById('profile-modal').hidden=true;boardCamera.x=0;boardCamera.y=0;boardCamera.scale=1;applyBoardCamera();for(let i=0;i<30;i++){const point=screenToBoard(200+(i%6)*220,100+Math.floor(i/6)*180);let m=createModule('clock',point.x,point.y);TeacherTilesTabs.add(m)}});await page.waitForTimeout(1500);const result=await page.evaluate(async()=>{let reads=0;const original=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(){reads++;return original.call(this)};const frames=[];let prev=performance.now(),id;const tick=t=>{frames.push(t-prev);prev=t;id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);await new Promise(r=>setTimeout(r,2000));cancelAnimationFrame(id);Element.prototype.getBoundingClientRect=original;return {tiles:document.querySelectorAll('.workspace .module').length,layoutReads:reads,frames:frames.length,over32ms:frames.filter(t=>t>32).length}});console.log(JSON.stringify({baseline,...result}));if(!baseline)assert(result.layoutReads<2000,'Idle layout should not run continuously');assert.deepEqual(errors,[])}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});