const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1280,height:720}}),requested=[];page.on('request',r=>{if(r.url().includes('/themes/scenes/'))requested.push(r.url())});await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname==='/__motion__')return r.fulfill({contentType:'text/html',body:'<style>body{margin:0;background:#07151d}canvas{display:block}</style><canvas id="stage" width="1280" height="720"></canvas>'});const f=path.join(process.cwd(),decodeURIComponent(u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)?r.fulfill({path:f}):r.abort()});await page.goto('http://tiles.test/__motion__');for(const script of ['flame-renderer','forest-motion','living-scenes','nature-scenes'])await page.addScriptTag({url:'http://tiles.test/tiles/shared/'+script+'.js'});assert.equal(requested.length,0,'no photo assets downloaded before selection');await page.evaluate(()=>TeacherTilesNatureScenes.prepare('campfire'));assert.equal(requested.length,1);const result=await page.evaluate(async()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'?null:original.call(this,type,...args)};const fallback=TeacherTilesFlameRenderer();HTMLCanvasElement.prototype.getContext=original;const a=fallback.draw(0).toDataURL(),b=fallback.draw(1).toDataURL();fallback.dispose();return {moves:a!==b}});assert(result.moves,'software fire animates');
const motion=await page.evaluate(async()=>{
 const result={};for(const theme of ['campfire','fireflies','christmas-tree']){
  await TeacherTilesNatureScenes.prepare(theme);const c=document.createElement('canvas');c.width=1600;c.height=900;const g=c.getContext('2d',{willReadFrequently:true});
  function sample(t,x,y,w,h){TeacherTilesNatureScenes.paint(g,1600,900,theme);TeacherTilesNatureScenes.draw(g,1600,900,theme,t);return g.getImageData(x,y,w,h).data}
  const area=theme==='christmas-tree'?[1040,20,450,630]:[50,40,420,460],a=sample(0,...area),b=sample(3,...area);let changed=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>12)changed++;result[theme]=changed;
 }return result;
});for(const [theme,pixels]of Object.entries(motion))assert(pixels>300,theme+' has visible foliage/light movement');console.log('Changed foliage/light pixels:',motion);
if(process.env.SCENE_PREVIEW_VIDEO){const video=await page.evaluate(async()=>{const c=document.querySelector('#stage'),g=c.getContext('2d'),base=document.createElement('canvas');base.width=1280;base.height=720;TeacherTilesNatureScenes.paint(base.getContext('2d'),1280,720,'campfire');const stream=c.captureStream(30),rec=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:3000000}),chunks=[];rec.ondataavailable=e=>chunks.push(e.data);const done=new Promise(resolve=>rec.onstop=resolve);rec.start();const start=performance.now();await new Promise(resolve=>{function tick(now){const t=(now-start)/1000;g.drawImage(base,0,0);TeacherTilesNatureScenes.draw(g,1280,720,'campfire',t);if(t<5)requestAnimationFrame(tick);else resolve()}requestAnimationFrame(tick)});rec.stop();await done;stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer()))});fs.writeFileSync(process.env.SCENE_PREVIEW_VIDEO,Buffer.from(video));}console.log('PASS: lazy asset loading and software flame fallback');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
