const fs=require('fs'),path=require('path'),assert=require('assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:1400,height:950}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{if(r.request().url().includes('sandbox/board-gate.js'))return r.abort();const u=new URL(r.request().url()),f=path.join(path.resolve(__dirname,'..'),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});await p.goto('http://tiles.test/');await p.evaluate(()=>{document.documentElement.classList.remove('sandbox-access-locked');const modal=document.querySelector('#settings-modal');for(const child of document.body.children)if(child!==modal)child.style.setProperty('visibility','hidden','important');modal.hidden=false;modal.style.setProperty('visibility','visible','important');modal.inert=false;});
async function search(kind,value){await p.locator('#'+kind+'-search').fill(value);await p.waitForTimeout(180);return p.locator('[data-settings-pane="'+kind+'"] '+(kind==='settings'?'.settings-row:visible':'.help-shortcut:visible,.help-mouse-list>div:visible,[data-help-topic]:visible'))}
await p.evaluate(()=>window.originalFontControl=document.querySelector('#settings-site-font-size'));
let rows=await search('settings','bigger text');assert.equal(await rows.count(),1);assert.equal(await rows.first().locator('strong').textContent(),'Font Size');
await p.locator('#settings-site-font-size').selectOption('110');assert.equal(await p.inputValue('#settings-search'),'bigger text');assert.equal(await p.evaluate(()=>appPreferences.siteFontSize),110);assert(await p.evaluate(()=>originalFontControl===document.querySelector('#settings-site-font-size')));
rows=await search('settings','quiet clicks');assert.equal(await rows.first().locator('strong').textContent(),'Mute UI Sounds');const mute=p.locator('#settings-ui-sfx-toggle'),before=await mute.getAttribute('aria-checked');await mute.click();assert.notEqual(await mute.getAttribute('aria-checked'),before);assert.equal(await p.inputValue('#settings-search'),'quiet clicks');
rows=await search('settings','master volume');await p.locator('#settings-master-volume').fill('65');await p.locator('#settings-master-volume').dispatchEvent('input');assert.equal(await p.locator('#settings-master-volume-value').textContent(),'65%');assert.equal(await p.evaluate(()=>appPreferences.masterVolume),65);
rows=await search('settings','langage');assert.equal(await rows.first().locator('strong').textContent(),'Interface Language');rows=await search('settings','volum');assert((await rows.count())>0);
await search('settings','zzzznomatch');assert(await p.locator('.panel-search__empty').isVisible());assert.equal(await p.locator('[data-settings-pane="settings"] .settings-card:visible').count(),0);await p.locator('#settings-search').press('Escape');assert(await p.locator('#settings-modal').isVisible());assert.equal(await p.inputValue('#settings-search'),'');assert.equal(await p.inputValue('#settings-site-font-size'),'110');assert.equal(await p.inputValue('#settings-master-volume'),'65');assert.equal(await p.locator('.panel-search-filtered').count(),0);
await p.locator('[data-settings-tab="help"]').click();rows=await search('help','spacebar');assert((await rows.count())>=1);assert((await rows.first().textContent()).includes('Recenter'));await p.locator('#help-search').press('Enter');assert.equal(await p.inputValue('#help-search'),'spacebar');assert(await rows.first().isVisible());
rows=await search('help','stop snapping');assert((await rows.first().textContent()).includes('disable tile snapping'));rows=await search('help','ctrl z');assert((await rows.first().textContent()).includes('Undo'));assert.equal(await p.locator('.panel-search__result').count(),0);
await p.evaluate(()=>{const topic=document.createElement('details');topic.dataset.helpTopic='test-video';topic.dataset.helpType='Video';topic.dataset.searchTitle='Organize Your Board';topic.dataset.searchKeywords='arrange classroom';topic.dataset.searchTranscript='Use the purple docking handle to combine activities.';topic.innerHTML='<summary>Organize Your Board</summary><p>A short walkthrough.</p>';document.querySelector('[data-settings-pane="help"]').append(topic)});
await search('help','purple docking');assert(await p.locator('[data-help-topic]').isVisible());await p.locator('[data-help-topic] summary').click();assert.equal(await p.locator('[data-help-topic]').evaluate(el=>el.open),true);assert.equal(await p.inputValue('#help-search'),'purple docking');await search('help','');assert(await p.locator('.help-shortcut').first().isVisible());assert(await p.locator('.help-tutorial-card').isVisible());assert.equal(await p.locator('[data-help-topic]').evaluate(el=>el.open),true);
await p.locator('[data-settings-tab="settings"]').click();rows=await search('settings','font');await p.setViewportSize({width:420,height:880});assert(await p.locator('.panel-search__field').first().evaluate(el=>el.getBoundingClientRect().right<=innerWidth));await p.locator('#settings-search').press('ArrowDown');assert.equal(await p.evaluate(()=>document.activeElement.id),'settings-site-font');assert.deepEqual(errors,[]);console.log('Passed in-place filtering, live dropdown/switch/slider edits, preserved controls and values, aliases, keyboard access, tutorial transcript matching and mobile layout.');}finally{await b.close()}})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
