import {tagEditor,discoveryShelves} from './discovery.js';
import './contract.js';
import {tileLabels} from './labels.js';
const contract=globalThis.TeacherTilesTemplateContract;
const make=(tag,className,value)=>{const e=document.createElement(tag);if(className)e.className=className;if(value!==undefined)e.textContent=value;return e;};
const button=(label,fn,cls='')=>{const b=make('button',cls,label);b.type='button';b.onclick=fn;return b;};
function dialog(title){const d=make('dialog','template-dialog'),header=make('header');header.append(make('h2','',title),button('×',()=>d.close(),'template-close'));d.append(header);document.body.append(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
function contentLines(tile){const lines=[];for(const e of tile.editables||[]){const doc=new DOMParser().parseFromString((e.html||'').replace(/<\/(p|div|li|h[1-3])>|<br\s*\/?\s*>/gi,'\n$&'),'text/html');if(doc.body.textContent)lines.push(doc.body.textContent.trim());}const scan=(v,key='')=>{if(typeof v==='string'&&!v.startsWith('data:')&&v.length&& !['version','border','borderColor','palette'].includes(key))lines.push(v);else if(v&&typeof v==='object')Object.entries(v).forEach(([k,val])=>scan(val,k));};scan(tile.special);return [...new Set(lines)];}
function placeholder(type){
 const e=make('div','template-placeholder');
 const art={meditation:'◉',timer:'◷',interactive:'◷',clock:'◷',egghatching:'🥚',flowerpots:'🌱',spreadsheet:'▦',coinflip:'◉',noise:'▥',squishy:'▣',glitterjar:'✧',fishtank:'🐠',piano:'♬',visualschedule:'☷'};
 e.append(make('span','',art[type]||'▦'));if(['egghatching','flowerpots','classmeter','collections','starchart','prizeboard','pbisconsole','punchcards','racer','classvsclass','seatingchart','attendance'].includes(type))e.append(make('small','','Connect your own class'));return e;
}
export function preview(snapshot){
 const wrap=make('div','template-preview'),objects=snapshot?.objects||[];
 const boxes=objects.map(o=>({o,x:Number(o.transform?.left)||0,y:Number(o.transform?.top)||0,w:(Number(o.transform?.width)||320)*(Number(o.transform?.uniformScale)||1),h:(Number(o.transform?.height)||240)*(Number(o.transform?.uniformScale)||1)}));
 if(!boxes.length){wrap.textContent='No tiles';return wrap;}
 const minX=Math.min(...boxes.map(b=>b.x)),minY=Math.min(...boxes.map(b=>b.y)),width=Math.max(...boxes.map(b=>b.x+b.w))-minX,height=Math.max(...boxes.map(b=>b.y+b.h))-minY;
 wrap.style.aspectRatio=String(Math.max(.7,Math.min(2,width/height)));for(const b of boxes){const tile=make('div','template-preview-tile');Object.assign(tile.style,{left:(b.x-minX)/width*96+2+'%',top:(b.y-minY)/height*96+2+'%',width:b.w/width*96+'%',height:b.h/height*96+'%'});const palette={yellow:'#fff6cd',pink:'#ffe9ef',blue:'#e7f1ff',green:'#e5f5ed',lavender:'#eee7fa',cream:'#fff9ed',charcoal:'#e3e6eb'};tile.style.backgroundColor=palette[b.o.dataset?.bg||b.o.dataset?.color]||'#fff';const lines=contentLines(b.o);tile.append(make('strong','',tileLabels[b.o.type]||b.o.type));if(lines.length)tile.append(make('span','',lines.join('\n').slice(0,350)));const src=b.o.special?.src||b.o.special?.image||b.o.sticker?.src;if(src){const img=make('img');img.src=src;img.alt='Template image';tile.append(img);}else if(b.o.sticker?.emoji)tile.append(make('span','',b.o.sticker.emoji));else if(!lines.length)tile.append(placeholder(b.o.type));wrap.append(tile);}return wrap;
}
function inspect(snapshot){const list=make('div','template-inspect');if(snapshot?.frames?.length)list.append(make('p','', 'Frames: '+snapshot.frames.map(f=>f.name).join(' · ')));for(const tile of snapshot?.objects||[]){const item=make('details'),summary=make('summary','',tileLabels[tile.type]||tile.type);item.append(summary);for(const page of [tile,...(tile.tabs?.items||[])]){item.append(make('p','',contentLines(page).join('\n')||'Default tile setup'));const visit=v=>{if(typeof v==='string'&&v.startsWith('data:image/')){const img=make('img');img.src=v;img.alt='Uploaded image for review';item.append(img);}else if(v&&typeof v==='object')Object.values(v).forEach(visit);};visit(page.special);visit(page.sticker);}list.append(item);}return list;}
export function createTemplateLibrary({element,call,getUid,capture,importBoard,knownTypes,renderPreview=preview,listBoards,readBoard,admin=false}){
 let mode=admin?'pending':'discover',cursor=null,identity=null,generation=0,busy=false,stopRotation=()=>{},tagGeneration=0;
 const cache=new Map(),heading=make('h2','',admin?'Board Templates':'Board Templates'),bar=make('div','template-toolbar'),status=make('p','template-status'),grid=make('div','template-grid'),search=make('input');search.type='search';search.placeholder='Search a word or tag';search.setAttribute('aria-label','Search templates');status.setAttribute('role','status');
 const browse=button(admin?'Pending review':'Discover',()=>setMode(admin?'pending':'discover')),mine=button(admin?'Reported':'My Submissions',()=>setMode(admin?'unlisted':'mine'));
 const refresh=button('Refresh',()=>load(true)),more=button('Load more',()=>load(false,true));more.hidden=true;
 const searchForm=make('form','template-search');searchForm.hidden=admin;searchForm.append(search,button('Search',()=>{}));searchForm.lastChild.type='submit';searchForm.onsubmit=e=>{e.preventDefault();load(true);};
 const allTemplates=admin?button('All Templates',()=>setMode('all')):null;bar.append(browse,mine);if(allTemplates)bar.append(allTemplates);bar.append(searchForm,refresh);if(!admin)bar.append(button('Upload a Board',()=>pickBoard(),'template-primary'));
 element.replaceChildren(heading,bar,status,grid,more);element.classList.add('template-library');
 const fit=()=>requestAnimationFrame(()=>{for(const box of element.querySelectorAll('.board-mini-object.is-real-tile')){const module=box.querySelector('.module');if(module&&box.clientWidth){const scale=Math.min(box.clientWidth/parseFloat(module.style.width),box.clientHeight/parseFloat(module.style.height));if(Number.isFinite(scale)&&scale>0)module.style.transform='scale('+scale+')';}}});element.addEventListener('templatepreviewresize',fit);new ResizeObserver(fit).observe(element);
 const request=async data=>{const uid=getUid(),result=await call(admin?'boardTemplateModeration':'boardTemplates',data);if(!uid||uid!==getUid())throw new Error('Your sign-in changed. Please reopen templates.');return result?.data||result;};
 function syncTabs(){allTemplates?.setAttribute('aria-pressed',String(mode==='all'));browse.setAttribute('aria-pressed',String(mode==='discover'||mode==='pending'));mine.setAttribute('aria-pressed',String(mode==='mine'||mode==='unlisted'));searchForm.hidden=(admin&&mode!=='all')||mode==='mine';}
 function setMode(next){mode=next;search.value='';syncTabs();load();}
 function art(snapshot,m={}){const wrap=make('div','template-board-art');wrap.append(renderPreview(snapshot));if(m.status==='pending')wrap.append(make('span','template-pending-badge','PENDING'));if(m.official){const logo=make('img','template-official-logo');logo.src='assets/profile/teachertiles-profile-logo.png';logo.alt='From TeacherTiles';wrap.append(logo);}return wrap;}
 function card(m){const c=button('',()=>detail(m),'template-card'),snapshot=m.preview||{objects:(m.layout||[]).map(v=>({type:v.type,transform:{left:v.x,top:v.y,width:v.w,height:v.h},dataset:{bg:v.color}}))};c.append(art(snapshot,m));const copy=make('div','template-card-copy');copy.append(make('strong','',m.title),make('span','',m.description),make('small','',m.official?'From TeacherTiles':(m.tags||[]).map(t=>'#'+t).join(' ')),make('small','template-state',(mode==='mine'||admin?m.status.replace('-',' ')+' · ':'')+(m.votes||0)+' upvotes · '+m.tileCount+' tiles'));if(m.feedback&&(mode==='mine'||admin))copy.append(make('p','',m.feedback));c.append(copy);return c;}
 function render(items,append=false){if(!append){stopRotation();grid.replaceChildren();grid.className='template-grid';}for(const m of items)grid.append(card(m));status.textContent=grid.childElementCount?'':'No templates here yet.';}
 function home(data){stopRotation();stopRotation=discoveryShelves(grid,data,card,tag=>loadTag(tag));status.textContent='';const region=make('div','template-tag-results'),controls=make('div','template-tag-controls'),label=make('strong','','All tags'),sort=make('select');sort.setAttribute('aria-label','Sort tagged boards');for(const [value,name] of [['rated','Highest rated'],['newest','Newest']]){const option=make('option','',name);option.value=value;sort.append(option);}controls.append(label,sort);const results=make('div','template-grid'),next=button('Load more tagged boards',()=>loadTag(activeTag,true)),notice=make('p','template-status');let activeTag='',tagCursor=data.highlyRated?.length===12?{id:data.highlyRated.at(-1).id,value:data.highlyRated.at(-1).votes}:null;next.hidden=!tagCursor;region.append(controls,notice,results,next);grid.lastElementChild.append(region);(data.highlyRated||[]).forEach(m=>results.append(card(m)));sort.onchange=()=>loadTag(activeTag);
  async function loadTag(tag,append=false){const ticket=++tagGeneration,parentGeneration=generation;activeTag=tag;label.textContent=tag?'#'+tag:'All tags';notice.textContent='Loading…';next.disabled=true;const key='tag:'+tag+':'+sort.value+':'+JSON.stringify(append?tagCursor:null);try{let result=cache.get(key);if(!result||Date.now()-result.at>=300000){result={...(await request({action:'list',tag,sort:sort.value,cursor:append?tagCursor:null})),at:Date.now()};cache.set(key,result);}if(ticket!==tagGeneration||parentGeneration!==generation)return;if(!append)results.replaceChildren();result.items.forEach(m=>results.append(card(m)));tagCursor=result.cursor;next.hidden=!tagCursor;notice.textContent=result.items.length?'':'No boards with this tag yet.';}catch(e){notice.textContent=e.message;}finally{next.disabled=false;}}
 }
 async function load(force=false,append=false){if(!getUid()){status.textContent='Sign in to browse and share templates.';return;}if(identity!==getUid()){reset();identity=getUid();}syncTabs();if(force)cache.clear();const token=++generation,isHome=!admin&&mode==='discover'&&!search.value.trim(),key=mode+':'+search.value.trim();refresh.disabled=more.disabled=true;status.textContent='Loading templates…';
  try{let data=!append&&cache.get(key);if(!data||Date.now()-data.at>=300000){data={...(await request({action:isHome?'discover':'list',mine:mode==='mine',status:mode,search:search.value,cursor:append?cursor:null})),at:Date.now()};if(!append)cache.set(key,data);}if(token!==generation)return;if(isHome){home(data);more.hidden=true;}else{render(data.items,append);cursor=data.cursor;more.hidden=!cursor;}}
  catch(e){if(token===generation)status.textContent=e.message||'Templates could not load.';}finally{if(token===generation)refresh.disabled=more.disabled=false;}
 }
 async function detail(meta){const d=dialog(meta.title),message=make('p','','Loading preview…');d.append(message);try{const data=await request({action:'detail',id:meta.id});if(!d.isConnected)return;message.textContent=data.meta.description;d.append(make('p','',data.meta.official?'Created by TeacherTiles':data.meta.tags.join(' · ')),make('p','template-rating',(data.meta.votes||0)+' upvotes'),art(data.snapshot,data.meta),inspect(data.snapshot));if(data.meta.feedback)d.append(make('p','','Reviewer feedback: '+data.meta.feedback));if(data.meta.warnings?.length){const notes=make('details');notes.append(make('summary','','Export adjustments'),make('p','',data.meta.warnings.join('\n')));d.append(notes);}
  const actions=make('div','template-actions'),feedback=make('textarea');feedback.placeholder=admin?'Feedback for the author':'Describe the problem';feedback.setAttribute('aria-label',feedback.placeholder);const act=async fn=>{actions.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){message.textContent=e.message;}finally{actions.querySelectorAll('button').forEach(b=>b.disabled=false);}};
  if(admin){actions.append(button('Delete template',()=>confirmDelete(data.meta,d),'template-reject'));if(!['pending','unlisted'].includes(data.meta.status)){d.append(actions);return;}const official=make('input');official.type='checkbox';official.checked=!!data.meta.official;const label=make('label','template-confirm','Official — From TeacherTiles');label.prepend(official);d.append(label,make('p','template-hint','Official boards appear on the TeacherTiles Curated shelf.'),make('p','template-review-check','Check every tile and tab for personal information, profanity, inappropriate imagery, and unsafe links before approving.'),feedback);for(const r of data.reports||[])d.append(make('p','','Report: '+r.reason));actions.append(button('Approve',()=>act(async()=>{await request({action:'review',id:meta.id,revision:data.meta.revision,decision:'approve',official:official.checked});d.close();load(true);}), 'template-approve'),button('Send back',()=>act(async()=>{await request({action:'review',id:meta.id,revision:data.meta.revision,decision:'send-back',feedback:feedback.value});d.close();load(true);}), 'template-reject'));
  }else if(mode==='mine'){actions.append(button('Edit details',()=>{d.close();editDetails(data.meta);}),button('Delete template',()=>confirmDelete(data.meta,d),'template-reject'));if(['sent-back','approved'].includes(data.meta.status))actions.append(button('Replace board',()=>{d.close();pickBoard(data.meta);}));}
  else {const importKey=Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join(''),vote=button(data.upvoted?'Upvoted':'Upvote',()=>act(async()=>{await request({action:'vote',id:meta.id});vote.textContent='Upvoted';message.textContent='Your upvote was recorded.';cache.clear();}));actions.append(button('Add to my boards',()=>act(async()=>{await importBoard(meta.id,importKey);d.close();}),'template-primary'),vote);d.append(feedback);actions.append(button(data.reported?'Reported':'Report',()=>act(async()=>{await request({action:'report',id:meta.id,reason:feedback.value});message.textContent='Report received. Thank you.';cache.clear();})));}d.append(actions);
 }catch(e){message.textContent=e.message;}}
 function confirmDelete(meta,parent){const d=dialog('Delete template?'),notice=make('p','','This removes '+meta.title+' from '+(admin?'the community and developer library':'your submissions and the community')+'. Boards people have already copied will stay in their accounts.');d.append(notice,button('Cancel',()=>d.close()),button('Delete permanently',async e=>{e.currentTarget.disabled=true;try{await request({action:'delete',id:meta.id});d.close();parent.close();load(true);}catch(error){notice.textContent=error.message;e.currentTarget.disabled=false;}},'template-reject'));}
 function fields(form,previous={}){const title=make('input'),description=make('textarea'),tags=tagEditor(previous.tags||[]);title.maxLength=90;title.minLength=3;title.required=true;title.value=previous.title||'';description.maxLength=1500;description.minLength=10;description.required=true;description.value=previous.description||'';for(const [name,input] of [['Title',title],['Description',description]]){const label=make('label','',name);label.append(input);form.append(label);}form.append(make('span','template-field-label','Tags'),tags.element);return ()=>({title:title.value,description:description.value,tags:tags.values()});}
 function editDetails(meta){const d=dialog('Edit template details'),form=make('form','template-upload'),values=fields(form,meta),notice=make('p','','Changes return this template to Pending review. Your upvote count is kept.'),save=button('Save changes',()=>{},'template-primary');save.type='submit';form.append(notice,save);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await request({action:'edit',id:meta.id,...values()});d.close();cache.clear();setMode('mine');}catch(error){notice.textContent=error.message;}finally{save.disabled=false;}};d.append(form);}
 async function pickBoard(previous){if(!getUid()){status.textContent='Sign in before uploading a board.';return;}const d=dialog('Choose a board to upload'),notice=make('p','','Loading your boards…'),boards=make('div','boards-grid template-board-picker');d.append(notice,boards);try{const choices=listBoards?await listBoards():[{id:'current',name:'Current board',snapshot:capture()}];if(!d.isConnected)return;notice.textContent='Select a board. Your original board will stay unchanged.';for(const b of choices){const c=button('',async()=>{c.disabled=true;try{const snapshot=readBoard?await readBoard(b.id):b.snapshot;if(!d.isConnected)return;d.close();upload(snapshot,previous||{title:b.name});}catch(e){notice.textContent=e.message;c.disabled=false;}},'board-card template-board-choice');c.append(art(b.snapshot||{theme:b.theme,objects:b.inlineObjects||b.previewObjects||[]}),make('strong','board-card__title',b.name));boards.append(c);}if(!choices.length)notice.textContent='Create a board first, then return here to share it.';}catch(e){notice.textContent=e.message;}}
 function upload(snapshot,previous){let result;try{result=contract.sanitize(snapshot,{knownTypes:knownTypes()});}catch(e){status.textContent=e.message;return;}const d=dialog(previous?.id?'Resubmit template':'Share a board template'),form=make('form','template-upload'),values=fields(form,previous);form.append(art(result.snapshot),inspect(result.snapshot),make('p','template-hint','Class links, student/PBIS records and activity history are excluded. This upload is an independent snapshot.'));if(result.warnings.length){const notes=make('details');notes.append(make('summary','','Export adjustments'),make('p','',result.warnings.join('\n')));form.append(notes);}const confirm=make('input');confirm.type='checkbox';confirm.required=true;const label=make('label','template-confirm','I reviewed every tile and image. This template contains no personal information or inappropriate content, and I have permission to share it.');label.prepend(confirm);const notice=make('p','template-status'),submit=button('Submit for approval',()=>{},'template-primary');submit.type='submit';form.append(label,notice,submit);form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;submit.disabled=true;try{await request({action:'submit',id:previous?.id,...values(),snapshot:result.snapshot,confirmPrivacy:confirm.checked});d.close();cache.clear();setMode('mine');}catch(error){notice.textContent=error.message;}finally{busy=false;submit.disabled=false;}};d.append(form);}
 function reset(){generation++;tagGeneration++;stopRotation();cache.clear();grid.replaceChildren();cursor=null;identity=null;document.querySelectorAll('.template-dialog').forEach(d=>d.close());}
 return {load,reset,element,open(){mode=admin?'pending':'discover';search.value='';return load();}};
}
