import './contract.js';
import {tileLabels} from './labels.js';
const contract=globalThis.TeacherTilesTemplateContract;
const make=(tag,className,value)=>{const e=document.createElement(tag);if(className)e.className=className;if(value!==undefined)e.textContent=value;return e;};
const button=(label,fn,cls='')=>{const b=make('button',cls,label);b.type='button';b.onclick=fn;return b;};
function dialog(title){const d=make('dialog','template-dialog'),header=make('header');header.append(make('h2','',title),button('×',()=>d.close(),'template-close'));d.append(header);document.body.append(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
function contentLines(tile){const lines=[];for(const e of tile.editables||[]){const doc=new DOMParser().parseFromString((e.html||'').replace(/<\/(p|div|li|h[1-3])>|<br\s*\/?\s*>/gi,'\n$&'),'text/html');if(doc.body.textContent)lines.push(doc.body.textContent.trim());}const scan=(v,key='')=>{if(typeof v==='string'&&!v.startsWith('data:')&&v.length&& !['version','border','borderColor','palette'].includes(key))lines.push(v);else if(v&&typeof v==='object')Object.entries(v).forEach(([k,val])=>scan(val,k));};scan(tile.special);return [...new Set(lines)];}
function placeholder(type){
 const e=make('div','template-placeholder');
 const art={meditation:'◉',timer:'◷',interactive:'◷',clock:'◷',egghatching:'🥚',flowerpots:'🌱',spreadsheet:'▦',coinflip:'◉',noise:'▥',squishy:'▣',glitterjar:'✧',fishtank:'🐠',piano:'♬',visualschedule:'☷'};
 e.append(make('span','',art[type]||'▦'));if(['egghatching','flowerpots','classmeter','collections','starchart','prizeboard','pbisconsole','punchcards','racer','classvsclass','seatingchart','attendance'].includes(type))e.append(make('small','','Connect your own class'));return e;
}
export function preview(snapshot){
 const wrap=make('div','template-preview'),objects=snapshot?.objects||[];
 const boxes=objects.map(o=>({o,x:Number(o.transform?.left)||0,y:Number(o.transform?.top)||0,w:(Number(o.transform?.width)||320)*(Number(o.transform?.uniformScale)||1),h:(Number(o.transform?.height)||240)*(Number(o.transform?.uniformScale)||1)}));
 if(!boxes.length){wrap.textContent='No tiles';return wrap;}
 const minX=Math.min(...boxes.map(b=>b.x)),minY=Math.min(...boxes.map(b=>b.y)),width=Math.max(...boxes.map(b=>b.x+b.w))-minX,height=Math.max(...boxes.map(b=>b.y+b.h))-minY;
 wrap.style.aspectRatio=String(Math.max(.7,Math.min(2,width/height)));for(const b of boxes){const tile=make('div','template-preview-tile');Object.assign(tile.style,{left:(b.x-minX)/width*96+2+'%',top:(b.y-minY)/height*96+2+'%',width:b.w/width*96+'%',height:b.h/height*96+'%'});const palette={yellow:'#fff6cd',pink:'#ffe9ef',blue:'#e7f1ff',green:'#e5f5ed',lavender:'#eee7fa',cream:'#fff9ed',charcoal:'#e3e6eb'};tile.style.backgroundColor=palette[b.o.dataset?.bg||b.o.dataset?.color]||'#fff';const lines=contentLines(b.o);tile.append(make('strong','',tileLabels[b.o.type]||b.o.type));if(lines.length)tile.append(make('span','',lines.join('\n').slice(0,350)));const src=b.o.special?.src||b.o.special?.image||b.o.sticker?.src;if(src){const img=make('img');img.src=src;img.alt='Template image';tile.append(img);}else if(b.o.sticker?.emoji)tile.append(make('span','',b.o.sticker.emoji));else if(!lines.length)tile.append(placeholder(b.o.type));wrap.append(tile);}return wrap;
}
function inspect(snapshot){const list=make('div','template-inspect');if(snapshot?.frames?.length)list.append(make('p','', 'Frames: '+snapshot.frames.map(f=>f.name).join(' · ')));for(const tile of snapshot?.objects||[]){const item=make('details'),summary=make('summary','',tileLabels[tile.type]||tile.type);item.append(summary);for(const page of [tile,...(tile.tabs?.items||[])]){item.append(make('p','',contentLines(page).join('\n')||'Default tile setup'));const visit=v=>{if(typeof v==='string'&&v.startsWith('data:image/')){const img=make('img');img.src=v;img.alt='Uploaded image for review';item.append(img);}else if(v&&typeof v==='object')Object.values(v).forEach(visit);};visit(page.special);visit(page.sticker);}list.append(item);}return list;}
export function createTemplateLibrary({element,call,getUid,capture,importBoard,knownTypes,admin=false}){
 let mode=admin?'pending':'discover',cursor=null,identity=null,loadedAt=0,generation=0,busy=false;
 const cache=new Map(),heading=make('h2','',admin?'Board Templates':'Community Board Templates'),bar=make('div','template-toolbar'),status=make('p','template-status'),grid=make('div','template-grid'),search=make('input');search.type='search';search.placeholder='Search a word or tag';search.setAttribute('aria-label','Search templates');
 const browse=button(admin?'Pending review':'Discover',()=>setMode(admin?'pending':'discover'));
 const mine=button(admin?'Reported':'My submissions',()=>setMode(admin?'unlisted':'mine'));
 const refresh=button('Refresh',()=>load(true));const more=button('Load more',()=>load(false,true));more.hidden=true;
 const searchForm=make('form','template-search');searchForm.hidden=admin;searchForm.append(search,button('Search',()=>{}));searchForm.lastChild.type='submit';searchForm.onsubmit=e=>{e.preventDefault();load(true);};
 bar.append(browse,mine,searchForm,refresh);if(!admin)bar.append(button('Upload current board',()=>upload(),'template-primary'));
 element.replaceChildren(heading,bar,status,grid,more);element.classList.add('template-library');
 const request=async data=>{const uid=getUid();const result=await call(admin?'boardTemplateModeration':'boardTemplates',data);if(!uid||uid!==getUid())throw new Error('Your sign-in changed. Please reopen templates.');return result?.data||result;};
 function setMode(next){mode=next;browse.setAttribute('aria-pressed',String(next==='discover'||next==='pending'));mine.setAttribute('aria-pressed',String(next==='mine'||next==='unlisted'));searchForm.hidden=admin||mode==='mine';load();}
 function render(items,append=false){if(!append)grid.replaceChildren();for(const m of items){const card=button('',()=>detail(m),'template-card');const art=m.layout?preview({objects:m.layout.map(v=>({type:v.type,transform:{left:v.x,top:v.y,width:v.w,height:v.h},dataset:{bg:v.color}}))}):make('span','template-card-art','▦');art.classList.add('template-card-art');card.append(art,make('strong','',m.title),make('span','',m.description),make('small','',m.tags?.map(t=>'#'+t).join(' ')||''),make('small','template-state',`${m.status.replace('-',' ')} · ${m.tileCount} tiles · ${m.votes||0} upvotes`));if(m.feedback)card.append(make('p','',m.feedback));grid.append(card);}status.textContent=grid.childElementCount?'':'No templates here yet.';}
 async function load(force=false,append=false){
  if(!getUid()){status.textContent='Sign in to browse and share templates.';return;}
  if(identity!==getUid()){reset();identity=getUid();}const token=++generation,key=mode+':'+search.value.trim();if(!append&&!force&&cache.has(key)&&Date.now()-cache.get(key).at<300000){const p=cache.get(key);cursor=p.cursor;render(p.items);more.hidden=!cursor;return;}
  status.textContent='Loading templates…';refresh.disabled=more.disabled=true;
  try{const data=await request({action:'list',mine:mode==='mine',status:mode,search:search.value,cursor:append?cursor:null});if(token!==generation)return;render(data.items,append);cursor=data.cursor;more.hidden=!cursor;loadedAt=Date.now();if(!append)cache.set(key,{...data,at:loadedAt});}
  catch(error){if(token===generation)status.textContent=error.message||'Templates could not load.';}finally{if(token===generation)refresh.disabled=more.disabled=false;}
 }
 async function detail(meta){const d=dialog(meta.title),message=make('p','','Loading preview…');d.append(message);try{
  const data=await request({action:'detail',id:meta.id});if(!d.isConnected)return;message.textContent=data.meta.description;d.append(make('p','',data.meta.tags.join(' · ')),preview(data.snapshot),make('p','template-hint','Layout preview. Expand each tile below to inspect all shared text and images.'),inspect(data.snapshot));
  if(data.meta.feedback)d.append(make('p','',`Reviewer feedback: ${data.meta.feedback}`));
  if(data.meta.warnings?.length){const notes=make('details');notes.append(make('summary','','Export adjustments'),make('p','',data.meta.warnings.join('\n')));d.append(notes);}
  const actions=make('div','template-actions'),feedback=make('textarea');feedback.placeholder=admin?'Feedback for the author':'Describe the problem';feedback.setAttribute('aria-label',feedback.placeholder);
  const act=async(fn)=>{actions.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(error){message.textContent=error.message;}finally{actions.querySelectorAll('button').forEach(b=>b.disabled=false);}};
  if(admin){d.append(make('p','template-review-check','Check every tile and tab for personal information, profanity, inappropriate imagery, and unsafe links before approving.'),feedback);for(const r of data.reports||[])d.append(make('p','',`Report (revision ${r.revision}): ${r.reason}`));actions.append(button('Approve',()=>act(async()=>{await request({action:'review',id:meta.id,revision:data.meta.revision,decision:'approve'});d.close();cache.clear();load(true);}), 'template-approve'),button('Send back',()=>act(async()=>{await request({action:'review',id:meta.id,revision:data.meta.revision,decision:'send-back',feedback:feedback.value});d.close();cache.clear();load(true);}), 'template-reject'));
  }else if(mode==='mine'){if(['sent-back','approved'].includes(data.meta.status))actions.append(button('Resubmit current board',()=>{d.close();upload(data.meta);}));}
  else {const importKey=Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');actions.append(button('Add to my boards',()=>act(async()=>{await importBoard(meta.id,importKey);d.close();}),'template-primary'),button(data.upvoted?'Upvoted':'Upvote',()=>act(async()=>{await request({action:'vote',id:meta.id});message.textContent='Your upvote was recorded.';cache.clear();})));d.append(feedback);actions.append(button(data.reported?'Reported':'Report',()=>act(async()=>{await request({action:'report',id:meta.id,reason:feedback.value});message.textContent='Report received. Thank you.';cache.clear();})));}
  d.append(actions);
 }catch(error){message.textContent=error.message;}}
 function upload(previous){if(!getUid()){status.textContent='Sign in before uploading a board.';return;}let result;try{result=contract.sanitize(capture(),{knownTypes:knownTypes()});}catch(error){status.textContent=error.message;return;}const d=dialog(previous?'Resubmit template':'Share a board template'),form=make('form','template-upload');
  const title=make('input'),description=make('textarea'),tags=make('input');title.maxLength=90;title.minLength=3;title.required=true;title.value=previous?.title||'';description.maxLength=1500;description.minLength=10;description.required=true;description.value=previous?.description||'';tags.value=previous?.tags?.join(', ')||'';
  for(const [label,input] of [['Title',title],['Description',description],['Tags (up to six, separated by commas)',tags]]){const l=make('label','',label);l.append(input);form.append(l);}form.append(preview(result.snapshot),inspect(result.snapshot),make('p','template-hint','This is a separate snapshot. Class links, student/PBIS records, account preferences and activity history are never included. Unsupported tile content resets. External images are omitted; embedded raster images can be reviewed.'));
  if(result.warnings.length){const notes=make('details');notes.open=true;notes.append(make('summary','','Review these changes before uploading'),make('p','',result.warnings.join('\n')));form.append(notes);}
  const confirm=make('input');confirm.type='checkbox';confirm.required=true;const label=make('label','template-confirm','I reviewed every tile and image. This template contains no student names, personal information, or inappropriate content, and I have permission to share it.');label.prepend(confirm);form.append(label);
  const notice=make('p','template-status'),submit=button('Submit for approval',()=>{},'template-primary');submit.type='submit';form.append(notice,submit);form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;submit.disabled=true;try{await request({action:'submit',id:previous?.id,title:title.value,description:description.value,tags:tags.value.split(','),snapshot:result.snapshot,confirmPrivacy:confirm.checked});d.close();cache.clear();setMode('mine');}catch(error){notice.textContent=error.message;}finally{busy=false;submit.disabled=false;}};d.append(form);
 }
 function reset(){generation++;cache.clear();grid.replaceChildren();cursor=null;loadedAt=0;identity=null;document.querySelectorAll('.template-dialog').forEach(d=>d.close());}
 return {load,reset,element};
}
