const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('tiles/spreadsheet/index.js','utf8'),sandbox);const calc=sandbox.window.TeacherTilesSpreadsheet.calculate;
assert.equal(calc({A1:'2',A2:'3',B1:'=SUM(A1:A2)*2'},'B1'),10);assert.equal(calc({A1:'=AVERAGE(B1:B2)',B1:'4',B2:'8'},'A1'),6);assert.throws(()=>calc({A1:'=B1',B1:'=A1'},'A1'),/#CYCLE/);assert.throws(()=>calc({A1:'=1/0'},'A1'),/#DIV/);assert.throws(()=>calc({A1:'=alert(1)'},'A1'),/#FORMULA/);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--unsafely-treat-insecure-origin-as-secure=http://tiles.test']});try{
const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('teacherTilesSandboxCoinsEnabled','true');window.Audio=class extends EventTarget{constructor(src){super();Object.assign(this,{src,paused:true,volume:1,currentTime:0,duration:20})}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}load(){}removeAttribute(){}cloneNode(){return new Audio(this.src)}};window.notices=[];window.Notification=class{static permission='granted';constructor(title,options){notices.push({title,...options})}}});
await page.route('**/*',r=>{const u=new URL(r.request().url()),f=path.join(process.cwd(),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});
await page.goto('http://tiles.test/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(1800);



await page.evaluate(()=>{document.getElementById('profile-modal').hidden=true;localStorage.setItem('teacherTilesOwnedShopPacks',JSON.stringify(['theme-underwater','theme-rainy-window']));window.dispatchEvent(new CustomEvent('teachertiles:shopownershipchange'))});
for(const [id,theme,name] of [['underwater','underwater-ocean','Underwater'],['rainy-window','rainy-window','Rainy Window']]){
assert.equal(await page.locator('[data-shop-product="theme-'+id+'"]').first().getAttribute('data-shop-price'),'450');assert.equal(await page.locator('#'+id+'-theme-fan [data-theme-choice]').count(),1);
await page.locator('#theme-shelf-toggle').evaluate(el=>el.click());await page.waitForTimeout(400);await page.getByRole('searchbox',{name:'Search themes'}).fill(name);await page.waitForTimeout(250);await page.locator('.theme-picker-pack-heading').filter({hasText:name}).click();await page.waitForTimeout(350);await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/shelf-'+id+'.png'});await page.locator('.theme-pack-fan [data-theme-choice="'+theme+'"]').click();assert.equal(await page.evaluate(()=>document.body.dataset.theme),theme);await page.locator('#asset-shelf-close').click();await page.waitForTimeout(600);assert(await page.locator('.animated-board-backdrop').isVisible());const before=await page.locator('.animated-board-backdrop').evaluate(c=>c.toDataURL());await page.waitForTimeout(140);assert.notEqual(await page.locator('.animated-board-backdrop').evaluate(c=>c.toDataURL()),before);await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/theme-'+id+'.png'});const saved=await page.evaluate(()=>TeacherTilesBoard.capture());await page.evaluate(()=>applyTeacherTheme('light'));assert.equal(await page.locator('.animated-board-backdrop').isVisible(),false);await page.evaluate(saved=>TeacherTilesBoard.load(saved),saved);assert.equal(await page.evaluate(()=>document.body.dataset.theme),theme);
}
await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(100);const still=await page.locator('.animated-board-backdrop').evaluate(c=>c.toDataURL());await page.waitForTimeout(150);assert.equal(await page.locator('.animated-board-backdrop').evaluate(c=>c.toDataURL()),still);await page.evaluate(()=>{localStorage.setItem('teacherTilesOwnedShopPacks','[]');applyTeacherTheme('underwater-ocean')});assert.equal(await page.evaluate(()=>document.body.dataset.theme),'light');assert.deepEqual(errors,[]);console.log('Animated themes: shelf selection, single-theme packs, 450-coin listings, animation, reduced motion, entitlement gating and board restore passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
