const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Jack/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname!=='tiles.test')return route.abort();if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:'<link rel="stylesheet" href="/templates/style.css"><style>body{font:15px system-ui;background:#f4f7fb;padding:30px}</style><main id="library"></main>'});const file=path.resolve(__dirname,'..','.'+url.pathname);if(fs.existsSync(file))return route.fulfill({path:file,contentType:file.endsWith('.js')?'text/javascript':'text/css'});return route.abort();});
 await page.goto('http://tiles.test/');await page.evaluate(async()=>{
  const {createTemplateLibrary}=await import('/templates/ui.js');window.calls=[];window.records=[];
  window.sample={objects:[{type:'sticky',transform:{left:0,top:0,width:230,height:180},editables:[{html:'<b>Welcome to our classroom!</b><p>Take a breath and get ready for a wonderful day.</p>'}]},{type:'richtext',transform:{left:260,top:0,width:340,height:180},editables:[{html:'<h2>Our morning routine</h2><ol><li>Unpack your bag</li><li>Read quietly</li><li>Share a kind word</li></ol>'}]},{type:'meditation',transform:{left:0,top:210,width:230,height:190},special:{inhaleSeconds:4,exhaleSeconds:6,durationSeconds:180}},{type:'egghatching',transform:{left:260,top:210,width:340,height:190},special:{activeClassId:'DO NOT SHARE'}}]};
  const call=async(name,d)=>{calls.push({...d,name});if(d.action==='list')return {items:records.filter(r=>name==='boardTemplateModeration'?r.status==='pending':d.mine||r.status==='approved'),cursor:null};if(d.action==='submit'){records=[{...d,id:'template1',status:'pending',revision:1,votes:0,tileCount:4}];return {id:'template1'};}if(d.action==='detail')return {meta:records[0],snapshot:records[0].snapshot};if(d.action==='review'){records[0].status=d.decision==='approve'?'approved':'sent-back';return {};}return {};};
  window.mount=admin=>{window.templateLibrary?.reset();window.templateLibrary=createTemplateLibrary({element:document.getElementById('library'),call,getUid:()=>admin?'admin':'author',capture:()=>sample,knownTypes:()=>['sticky','richtext','meditation','egghatching'],importBoard:async()=>{window.imported=true;},admin});return templateLibrary.load();};await mount(false);
 });
 await page.getByRole('button',{name:'Upload current board'}).click();await page.getByLabel('Title',{exact:true}).fill('A welcoming morning');await page.getByLabel('Description',{exact:true}).fill('A calm start with a welcome note, morning routine, breathing timer, and an empty class reward tile.');await page.getByLabel('Tags (up to six, separated by commas)').fill('morning, wellbeing');
 assert(!await page.locator('dialog').innerText().then(s=>s.includes('DO NOT SHARE')));await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Submit for approval'}).click();await page.locator('.template-card').waitFor();assert((await page.locator('.template-card').innerText()).toLowerCase().includes('pending'));
 const count=await page.evaluate(()=>calls.length);await page.evaluate(()=>templateLibrary.load());assert.equal(await page.evaluate(()=>calls.length),count);
 await page.evaluate(()=>mount(true));await page.locator('.template-card').click();await page.getByRole('button',{name:'Approve',exact:true}).waitFor();
 const shots=process.env.TT_SCREENSHOT_DIR;if(shots){fs.mkdirSync(shots,{recursive:true});await page.screenshot({path:path.join(shots,'board-template-review.png'),fullPage:true});}
 await page.getByRole('button',{name:'Approve',exact:true}).click();await page.getByText('No templates here yet.').waitFor();
 await page.evaluate(()=>mount(false));await page.locator('.template-card').click();await page.getByRole('button',{name:'Add to my boards'}).click();assert(await page.evaluate(()=>window.imported));
 await page.evaluate(()=>templateLibrary.reset());assert.equal(await page.locator('.template-card').count(),0);assert.deepEqual(errors,[]);console.log('PASS: upload preview, private-state exclusion, pending status, cached lists, admin approval and board import UI');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
