const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Jack/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname!=='tiles.test')return route.abort();if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:'<link rel="stylesheet" href="/templates/style.css"><style>body{font:15px system-ui;background:#f4f7fb;padding:30px}</style><main id="library"></main>'});const file=path.resolve(__dirname,'..','.'+url.pathname);if(fs.existsSync(file))return route.fulfill({path:file,contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'image/svg+xml'});return route.abort();});
 await page.goto('http://tiles.test/');
 const appSource=fs.readFileSync(path.resolve(__dirname,'../firebase-auth.js'),'utf8');
 await page.addScriptTag({content:appSource.slice(appSource.indexOf('function previewThemeClass('),appSource.indexOf('async function deleteBoard('))+appSource.slice(appSource.indexOf('function createBoardPreview('),appSource.indexOf('function createBoardCard('))});
 await page.evaluate(html=>{const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('template').forEach(t=>document.body.append(t.cloneNode(true)));doc.querySelectorAll('link[rel=stylesheet]').forEach(l=>{if(!l.href.startsWith('https://fonts.'))document.head.append(l.cloneNode(true));});},fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'));
 await page.addStyleTag({content:'html,body{overflow:auto!important;height:auto!important}body{padding:30px!important;background:#f4f7fb!important}'});
 await page.evaluate(async()=>{
  const {createTemplateLibrary}=await import('/templates/ui.js');window.calls=[];window.records=[];
  window.sample={objects:[{type:'sticky',transform:{left:0,top:0,width:230,height:180},editables:[{html:'<b>Welcome to our classroom!</b><p>Take a breath and get ready for a wonderful day.</p>'}]},{type:'richtext',transform:{left:260,top:0,width:340,height:180},editables:[{html:'<h2>Our morning routine</h2><ol><li>Unpack your bag</li><li>Read quietly</li><li>Share a kind word</li></ol>'}]},{type:'meditation',transform:{left:0,top:210,width:230,height:190},special:{inhaleSeconds:4,exhaleSeconds:6,durationSeconds:180}},{type:'egghatching',transform:{left:260,top:210,width:340,height:190},special:{activeClassId:'DO NOT SHARE'}}]};
  const call=async(name,d)=>{calls.push({...d,name});if(d.action==='discover'){const approved=records.filter(r=>r.status==='approved');return {featured:approved,curated:approved.filter(r=>r.official),highlyRated:approved,tags:['morning','math']};}if(d.action==='edit'){Object.assign(records[0],d,{status:'pending'});return {};}if(d.action==='delete'){records=[];return {};}if(d.action==='list')return {items:records.filter(r=>name==='boardTemplateModeration'?r.status==='pending':d.mine||r.status==='approved'),cursor:null};if(d.action==='submit'){records=[{...d,id:'template1',status:'pending',revision:1,votes:12,tileCount:4,preview:d.snapshot}];return {id:'template1'};}if(d.action==='detail')return {meta:records[0],snapshot:records[0].snapshot};if(d.action==='review'){records[0].official=d.official;records[0].status=d.decision==='approve'?'approved':'sent-back';return {};}return {};};
  window.mount=admin=>{window.templateLibrary?.reset();window.templateLibrary=createTemplateLibrary({element:document.getElementById('library'),call,getUid:()=>admin?'admin':'author',capture:()=>sample,renderPreview:snapshot=>createBoardPreview({theme:snapshot.theme,inlineObjects:snapshot.objects}),knownTypes:()=>['sticky','richtext','meditation','egghatching'],importBoard:async()=>{window.imported=true;},admin});return templateLibrary.load();};await mount(false);
 });
 await page.getByRole('button',{name:'Upload a Board'}).click();await page.getByRole('button',{name:'Current board',exact:false}).click();await page.getByLabel('Title',{exact:true}).fill('A welcoming morning');await page.getByLabel('Description',{exact:true}).fill('A calm start with a welcome note, morning routine, breathing timer, and an empty class reward tile.');await page.getByLabel('Add a tag').fill('morning');await page.getByLabel('Add a tag').press('Enter');await page.getByLabel('Add a tag').fill('wellbeing');await page.getByLabel('Add a tag').press('Enter');await page.locator('.template-tag').last().hover();await page.getByRole('button',{name:'Remove tag wellbeing'}).click();assert.equal(await page.locator('.template-tag').count(),1);
 assert(!await page.locator('dialog').innerText().then(s=>s.includes('DO NOT SHARE')));await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Submit for approval'}).click();await page.locator('.template-card').waitFor();assert((await page.locator('.template-card').innerText()).toLowerCase().includes('pending'));
 const count=await page.evaluate(()=>calls.length);await page.evaluate(()=>templateLibrary.load());assert.equal(await page.evaluate(()=>calls.length),count);
 await page.evaluate(()=>mount(true));await page.locator('.template-card').click();await page.getByRole('button',{name:'Approve',exact:true}).waitFor();
 const shots=process.env.TT_SCREENSHOT_DIR;if(shots){fs.mkdirSync(shots,{recursive:true});await page.screenshot({path:path.join(shots,'board-template-review.png'),fullPage:true});}
 await page.getByRole('checkbox',{name:'Official — From TeacherTiles'}).check();await page.getByRole('button',{name:'Approve',exact:true}).click();await page.getByText('No templates here yet.').waitFor();
 await page.evaluate(()=>mount(false));await page.getByRole('heading',{name:'Featured Boards',exact:true}).waitFor();assert(await page.locator('.template-feature-slide .is-real-tile').count()>0);await page.locator('.template-feature-slide').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished)));if(shots)await page.screenshot({path:path.join(shots,'template-discover-shelves.png'),fullPage:true});assert.equal(await page.locator('.template-shelf').count(),4);assert(await page.locator('.template-official-logo').count());await page.locator('.template-card').first().click();await page.getByRole('button',{name:'Add to my boards'}).click();assert(await page.evaluate(()=>window.imported));
 await page.getByRole('button',{name:'My submissions',exact:true}).click();await page.locator('.template-card').click();await page.getByRole('button',{name:'Edit details'}).click();await page.getByLabel('Title',{exact:true}).fill('Updated morning');await page.getByRole('button',{name:'Save changes'}).click();await page.locator('.template-card').click();await page.getByRole('button',{name:'Delete template',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.evaluate(()=>records.length),1);await page.getByRole('button',{name:'Delete template',exact:true}).click();await page.getByRole('button',{name:'Delete permanently',exact:true}).click();await page.getByText('No templates here yet.').waitFor();await page.evaluate(()=>templateLibrary.reset());assert.equal(await page.locator('.template-card').count(),0);await page.mouse.move(0,0);const rotation=await page.evaluate(async()=>{const {discoveryShelves}=await import('/templates/discovery.js');const root=document.createElement('div');document.body.append(root);let tick;const original=window.setInterval;window.setInterval=fn=>{tick=fn;return 0;};const count=calls.length;const clean=discoveryShelves(root,{featured:[{title:'One'},{title:'Two'}],curated:[],highlyRated:[],tags:[]},m=>{const b=document.createElement('button');b.textContent=m.title;return b;},()=>{});window.setInterval=original;tick();const visible=[...root.querySelectorAll('.template-feature-slide')].filter(e=>!e.hidden).map(e=>e.textContent);clean();root.remove();return {visible,reads:calls.length-count};});assert.deepEqual(rotation,{visible:['Two'],reads:0});assert.deepEqual(errors,[]);console.log('PASS: upload preview, private-state exclusion, pending status, cached lists, admin approval and board import UI');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
