const fs=require('fs'),path=require('path'),assert=require('assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:1400,height:950}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{if(r.request().url().includes('sandbox/board-gate.js'))return r.abort();const u=new URL(r.request().url()),f=path.join(path.resolve(__dirname,'..'),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});await p.goto('http://tiles.test/');await p.evaluate(()=>{document.documentElement.classList.remove('sandbox-access-locked');const modal=document.querySelector('#settings-modal');for(const child of document.body.children)if(child!==modal)child.style.setProperty('visibility','hidden','important');modal.hidden=false;modal.style.setProperty('visibility','visible','important');modal.inert=false;});
async function search(kind,value){await p.locator('#'+kind+'-search').fill(value);await p.waitForTimeout(180);return p.locator('#'+kind+'-search-results .panel-search__result')}
let rows=await search('settings','bigger text');assert.equal(await rows.first().locator('strong').textContent(),'Font Size');await rows.first().click();assert.equal(await p.locator('#settings-site-font-size').evaluate(el=>el===document.activeElement),true);assert.equal(await p.inputValue('#settings-search'),'');
rows=await search('settings','quiet clicks');assert.equal(await rows.first().locator('strong').textContent(),'Mute UI Sounds');rows=await search('settings','langage');assert.equal(await rows.first().locator('strong').textContent(),'Interface Language');rows=await search('settings','volum');assert((await rows.count())>0);await search('settings','zzzznomatch');assert(await p.locator('.panel-search__empty').isVisible());await p.locator('#settings-search').press('Escape');assert(await p.locator('#settings-modal').isVisible());assert.equal(await p.inputValue('#settings-search'),'');
await p.locator('[data-settings-tab="help"]').click();rows=await search('help','spacebar');assert((await rows.first().textContent()).includes('Recenter'));await p.locator('#help-search').press('Enter');assert.equal(await p.inputValue('#help-search'),'');assert(await p.locator('.panel-search-target').count()>0);
rows=await search('help','stop snapping');assert((await rows.first().textContent()).includes('disable tile snapping'));rows=await search('help','ctrl z');assert((await rows.first().textContent()).includes('Undo'));
await p.evaluate(()=>{const topic=document.createElement('details');topic.dataset.helpTopic='test-video';topic.dataset.helpType='Video';topic.dataset.searchTitle='Organize Your Board';topic.dataset.searchKeywords='arrange classroom';topic.dataset.searchTranscript='Use the purple docking handle to combine activities.';topic.innerHTML='<summary>Organize Your Board</summary><p>A short walkthrough.</p>';document.querySelector('[data-settings-pane="help"]').append(topic)});rows=await search('help','purple docking');assert.equal(await rows.count(),1);assert((await rows.first().textContent()).includes('Video'));await rows.first().click();assert.equal(await p.locator('[data-help-topic]').evaluate(el=>el.open),true);
await p.locator('[data-settings-tab="settings"]').click();rows=await search('settings','font');await p.setViewportSize({width:420,height:880});assert(await p.locator('.panel-search__field').first().evaluate(el=>el.getBoundingClientRect().right<=innerWidth));assert.deepEqual(errors,[]);console.log('Passed ranking, aliases, partial matches, no results, Escape/Enter, focus navigation, tutorial transcript discovery, expandable targets, and mobile layout.');}finally{await b.close()}})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
