const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Jack/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname!=='tiles.test')return route.abort();if(url.pathname==='/sandbox/')return route.fulfill({contentType:'text/html',body:'<link rel="stylesheet" href="sandbox/portal.css"><link rel="stylesheet" href="templates/style.css"><style>body{overflow:auto;padding:30px}</style><main id="test-root"></main>'});if(url.pathname==='/sandbox/board.html')return route.fulfill({contentType:'text/html',body:html});const file=path.join(root,url.pathname.replace(/^\/sandbox\//,''));return fs.existsSync(file)&&fs.statSync(file).isFile()?route.fulfill({path:file}):route.abort();});
 await page.goto('http://tiles.test/sandbox/');await page.evaluate(async html=>{
  const doc=new DOMParser().parseFromString(html,'text/html'),form=doc.getElementById('bug-report-form');document.getElementById('test-root').append(form);window.sent=[];
  const {setupBugReports}=await import('./bug-reports.js');setupBugReports(async(name,data)=>{sent.push({name,...data});return {submitted:true};});
 },html);
 await page.getByLabel('Category',{exact:true}).selectOption('Other');await page.getByLabel('Title',{exact:true}).fill('A reproducible display issue');await page.getByLabel('What happened?').fill('Open a board, resize a tile, and the display becomes too small.');await page.getByRole('button',{name:'Submit Ticket'}).click();await page.getByText('Ticket sent. Track it in In Progress Tickets.').waitFor();assert.equal(await page.evaluate(()=>sent[0].category),'Other');
 await page.evaluate(async()=>{document.getElementById('test-root').replaceChildren();const {createBugReports}=await import('./sandbox/bug-reports.js');window.report={id:'a'.repeat(64),title:sent[0].title,category:'Other',description:sent[0].description,authorEmail:'teacher@example.com',status:'new',revision:1,createdAt:Date.now()};window.reportCalls=[];window.panel=createBugReports(async(name,d)=>{reportCalls.push(d);if(d.action==='list')return {data:{items:[report],cursor:null}};if(d.action==='detail')return {data:{report:{...report}}};report.status=d.status;report.revision++;return {data:{status:d.status}};});panel.element.hidden=false;document.getElementById('test-root').append(panel.element);await panel.load();});
 await page.locator('.bug-report-row').click();await page.getByRole('button',{name:'In Progress',exact:true}).click();await page.locator('.bug-report-row[data-status="in-progress"]').waitFor();await page.locator('.bug-report-row').click();await page.getByRole('button',{name:'Closed',exact:true}).click();await page.locator('.bug-report-row[data-status="complete"]').waitFor();const reads=await page.evaluate(()=>reportCalls.length);await page.evaluate(()=>panel.load());assert.equal(await page.evaluate(()=>reportCalls.length),reads);
 await page.evaluate(async()=>{
  panel.reset();document.getElementById('test-root').replaceChildren();const {createTemplateLibrary}=await import('./templates/ui.js'),{adminBoardPreview}=await import('./sandbox/board-preview.js');const board={theme:'light',objects:[{id:'one',type:'sticky',dataset:{color:'yellow'},transform:{left:500,top:500,width:300,height:240},editables:[{index:0,html:'Read a book and share your favorite part.'}]}]};window.template={id:'test',title:'Reading routine',description:'A simple routine for reading time.',tags:['reading'],status:'pending',revision:1,votes:0,tileCount:1,preview:board};window.templateCalls=[];window.library=createTemplateLibrary({element:document.getElementById('test-root'),getUid:()=> 'admin',admin:true,renderPreview:adminBoardPreview,call:async(name,d)=>{templateCalls.push(d);if(d.action==='list')return {items:[template],cursor:null};if(d.action==='detail')return {meta:template,snapshot:board};return {deleted:true};}});await library.load();
 });
 await page.locator('.template-pending-badge').waitFor();await page.locator('.admin-board-preview .board-mini-object.is-real-tile').waitFor();assert((await page.locator('.admin-board-preview .sticky-editor').textContent()).includes('Read a book'));
 await page.getByRole('button',{name:'All Templates',exact:true}).click();await page.getByRole('searchbox',{name:'Search templates'}).fill('reading');await page.getByRole('button',{name:'Search',exact:true}).click();await page.waitForFunction(()=>templateCalls.at(-1).search==='reading');await page.locator('.template-card').click();await page.getByRole('button',{name:'Delete template',exact:true}).click();await page.getByRole('button',{name:'Delete permanently',exact:true}).click();await page.waitForFunction(()=>templateCalls.some(c=>c.action==='delete'));
 await page.evaluate(async()=>{library.reset();document.getElementById('test-root').replaceChildren();const {tagEditor}=await import('./templates/discovery.js');window.editor=tagEditor();const d=document.createElement('div');d.className='template-dialog';d.style.width='600px';d.append(editor.element);document.getElementById('test-root').append(d);});
 const input=page.getByLabel('Add a tag'),width=await input.evaluate(e=>e.getBoundingClientRect().width);for(let i=0;i<10;i++){await input.fill('tag'+i);await input.press('Enter');}assert.equal(await page.locator('.template-tag').count(),10);assert.equal(await input.evaluate(e=>e.getBoundingClientRect().width),width);assert(await page.locator('.template-tags').evaluate(e=>e.getBoundingClientRect().top>e.previousElementSibling.getBoundingClientRect().bottom));await input.fill('eleventh');await input.press('Enter');assert.equal(await page.locator('.template-tag').count(),10);await input.fill('');await page.locator('.template-tag').last().hover();await page.getByRole('button',{name:'Remove tag tag9'}).click();assert.equal(await page.locator('.template-tag').count(),9);assert.deepEqual(errors,[]);console.log('PASS: bug submission/status UI, real admin tile previews, pending badge, all-template search/deletion, and ten tags below a fixed-width input');
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
