const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('tiles/spreadsheet/index.js','utf8'),sandbox);const calc=sandbox.window.TeacherTilesSpreadsheet.calculate;
assert.equal(calc({A1:'2',A2:'3',B1:'=SUM(A1:A2)*2'},'B1'),10);assert.equal(calc({A1:'=AVERAGE(B1:B2)',B1:'4',B2:'8'},'A1'),6);assert.throws(()=>calc({A1:'=B1',B1:'=A1'},'A1'),/#CYCLE/);assert.throws(()=>calc({A1:'=1/0'},'A1'),/#DIV/);assert.throws(()=>calc({A1:'=alert(1)'},'A1'),/#FORMULA/);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--unsafely-treat-insecure-origin-as-secure=http://tiles.test']});try{
const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('teacherTilesSandboxCoinsEnabled','true');window.Audio=class extends EventTarget{constructor(src){super();Object.assign(this,{src,paused:true,volume:1,currentTime:0,duration:20})}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}load(){}removeAttribute(){}cloneNode(){return new Audio(this.src)}};window.notices=[];window.Notification=class{static permission='granted';constructor(title,options){notices.push({title,...options})}}});
await page.route('**/*',r=>{const u=new URL(r.request().url()),f=path.join(process.cwd(),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});
await page.goto('http://tiles.test/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(1800);

await page.evaluate(()=>{document.getElementById('profile-modal').hidden=true;boardCamera.x=0;boardCamera.y=0;boardCamera.scale=1;applyBoardCamera();for(const [type,x,y] of [['noise',300,250],['squishy',800,250],['spreadsheet',500,740],['reminders',1220,250],['chime',1200,750]])createModule(type,x,y)});
const noise=page.locator('.noise-modern'),squishy=page.locator('.squishy-module'),sheet=page.locator('.spreadsheet-module');assert.equal(await noise.count(),1);assert.equal(await squishy.count(),1);
await page.evaluate(()=>{window.trackStops=0;window.gains=[];Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>({getTracks:()=>[{stop:()=>trackStops++}]})}});window.AudioContext=class{constructor(){this.state='running'}resume(){return Promise.resolve()}close(){this.state='closed';return Promise.resolve()}createAnalyser(){return {getByteTimeDomainData:a=>a.fill(190)}}createMediaStreamSource(){return {connect(){}}}createMediaElementSource(){return {connect(){},disconnect(){}}}createGain(){const gain={gain:{value:1},connect(){},disconnect(){}};gains.push(gain);return gain}}});
await noise.locator('.noise-start').click();await page.waitForTimeout(450);assert(await noise.evaluate(el=>el.classList.contains('nm-live')));assert.notEqual(await noise.locator('.nm-value').innerText(),'—');await noise.evaluate(el=>el._deactivate());assert.equal(await page.evaluate(()=>trackStops),1);assert.equal(await noise.evaluate(el=>el.classList.contains('nm-live')),false);
await page.evaluate(()=>{appPreferences.masterVolume=100;const m=document.querySelector('.chime-module');TeacherTilesTileAudio.set(m,{volume:150});});assert.equal(await page.locator('.chime-module .tile-audio-volume').getAttribute('max'),'150');assert.equal(await page.evaluate(()=>TeacherTilesTileAudio.level(document.querySelector('.chime-module'))),1.5);assert(await page.evaluate(()=>gains.some(g=>g.gain.value>1)));
const canvas=squishy.locator('canvas'),rest=await canvas.evaluate(el=>el.toDataURL()),r=await canvas.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width*.65,r.y+r.height*.65,{steps:10});await page.waitForTimeout(250);assert.notEqual(await canvas.evaluate(el=>el.toDataURL()),rest);await page.mouse.up();await page.waitForTimeout(3000);assert.equal(await canvas.evaluate(el=>el.toDataURL()),rest);await squishy.evaluate(el=>el._deactivate());assert.equal(await canvas.evaluate(el=>el.toDataURL()),rest);
await sheet.hover();await sheet.locator('[data-cell=A1]').fill('hello');await sheet.locator('[data-cell=A1]').press('Space');assert.equal(await sheet.locator('[data-cell=A1]').inputValue(),'hello ');
await sheet.locator('[data-cell=A1]').click({button:'right'});assert(await page.locator('.sheet-context-menu').isVisible());await noise.locator('.noise-start').click();assert.equal(await page.locator('.sheet-context-menu').isVisible(),false);assert.equal(await sheet.locator('.is-selected').count(),0);await page.mouse.move(1450,950);await page.waitForTimeout(300);assert.equal(await sheet.locator('.sheet-formula-row').isVisible(),false);assert.equal(await sheet.locator('.sheet-toolbar').isVisible(),false);
await page.evaluate(()=>{boardCamera.scale=.6;applyBoardCamera();document.querySelector('.noise-start').focus()});await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>boardCamera.scale),1);assert(await noise.evaluate(el=>el.classList.contains('nm-live')));
await page.evaluate(()=>{boardCamera.scale=.7;applyBoardCamera();document.querySelector('.noise-range').focus()});await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>boardCamera.scale),1);assert.equal(await page.locator('.reminders-empty').count(),0);const add=await page.locator('.reminders-add').boundingBox(),rem=await page.locator('.reminders-module').boundingBox();assert(Math.abs(add.x+add.width/2-rem.x-rem.width/2)<2);
await page.locator('#theme-shelf-toggle').evaluate(el=>el.click());assert((await page.locator('.theme-pack-sample .theme-card__preview').count())>0);assert((await page.locator('.theme-pack-sample .theme-card__copy').count())>0);await page.locator('#asset-shelf-close').click();
await page.evaluate(()=>{boardCamera.x=0;boardCamera.y=0;boardCamera.scale=1;applyBoardCamera();const placements={noise:[40,100],squishy:[530,100],reminders:[950,100],spreadsheet:[40,540],chime:[800,620]};for(const m of document.querySelectorAll('.workspace .module')){const p=placements[m.dataset.type];if(p){m.style.left=p[0]+'px';m.style.top=p[1]+'px'}}});await page.mouse.move(1450,950);await page.waitForTimeout(400);await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/sel-noise-squishy.png'});
await page.evaluate(()=>{window.popCount=0;const original=playUiSfx;window.originalPop=original;playUiSfx=(...args)=>{if(args[0]==='click')popCount++;return original(...args)}});await squishy.locator('.module-delete').evaluate(el=>el.click());assert.equal(await page.evaluate(()=>popCount),1);
await page.evaluate(()=>{const m=document.querySelector('.noise-modern');m._deactivate();window.resolveMic=null;navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>resolveMic=resolve);m.querySelector('.noise-start').click();m._deactivate();resolveMic({getTracks:()=>[{stop:()=>trackStops++}]})});await page.waitForTimeout(100);assert.equal(await noise.evaluate(el=>el.classList.contains('nm-live')),false);
await page.evaluate(()=>TeacherTilesBoard.load(TeacherTilesBoard.capture()));assert.equal(await page.locator('.chime-module').evaluate(el=>TeacherTilesTileAudio.state(el).volume),150);
await page.evaluate(()=>{const m=document.querySelector('.noise-modern');m._boardSetState({threshold:55,sensitivity:135,view:'waveform'});window.noiseSize={width:m.style.width,height:m.style.height};TeacherTilesBoard.load(TeacherTilesBoard.capture())});assert.deepEqual(await page.locator('.noise-modern').evaluate(el=>el._boardGetState()),{version:1,threshold:55,sensitivity:135,view:'waveform'});assert.deepEqual(await page.locator('.noise-modern').evaluate(el=>({width:el.style.width,height:el.style.height})),await page.evaluate(()=>noiseSize));assert.deepEqual(errors,[]);console.log('Space routing, delete pop, spreadsheet focus/menu/hover, centered reminders, theme previews, audio boost, noise microphone lifecycle, squishy deformation and save/restore passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
