const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('tiles/spreadsheet/index.js','utf8'),sandbox);const calc=sandbox.window.TeacherTilesSpreadsheet.calculate;
assert.equal(calc({A1:'2',A2:'3',B1:'=SUM(A1:A2)*2'},'B1'),10);assert.equal(calc({A1:'=AVERAGE(B1:B2)',B1:'4',B2:'8'},'A1'),6);assert.throws(()=>calc({A1:'=B1',B1:'=A1'},'A1'),/#CYCLE/);assert.throws(()=>calc({A1:'=1/0'},'A1'),/#DIV/);assert.throws(()=>calc({A1:'=alert(1)'},'A1'),/#FORMULA/);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--unsafely-treat-insecure-origin-as-secure=http://tiles.test']});try{
const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('teacherTilesSandboxCoinsEnabled','true');window.Audio=class extends EventTarget{constructor(src){super();Object.assign(this,{src,paused:true,volume:1,currentTime:0,duration:20})}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}load(){}removeAttribute(){}cloneNode(){return new Audio(this.src)}};window.notices=[];window.Notification=class{static permission='granted';constructor(title,options){notices.push({title,...options})}}});
await page.route('**/*',r=>{const u=new URL(r.request().url()),f=path.join(process.cwd(),decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));return u.hostname==='tiles.test'&&fs.existsSync(f)&&fs.statSync(f).isFile()?r.fulfill({path:f}):r.abort()});
await page.goto('http://tiles.test/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(1800);


await page.evaluate(()=>{document.getElementById('profile-modal').hidden=true;boardCamera.x=0;boardCamera.y=0;boardCamera.scale=1;applyBoardCamera();for(const [type,x,y,w,h] of [['sentenceexpansion',60,110,560,600],['spreadsheet',660,110,740,400],['noise',700,550,450,350]]){const m=createModule(type,x,y);Object.assign(m.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'})}});
const sentence=page.locator('.sentence-expansion-module');assert.equal(await sentence.getByRole('textbox',{name:'Starting subject',exact:true}).textContent(),'subject');
await sentence.getByRole('textbox',{name:'Starting subject',exact:true}).fill('The cat');await sentence.getByRole('textbox',{name:'Starting predicate',exact:true}).fill('slept');assert.equal(await sentence.getByRole('textbox',{name:'Expanded subject',exact:true}).textContent(),'The cat');
await sentence.getByRole('textbox',{name:'Expanded subject',exact:true}).fill('The fluffy cat');await sentence.getByRole('textbox',{name:'Expanded predicate',exact:true}).fill('slept on the warm rug');await page.keyboard.press('Enter');assert.equal(await sentence.evaluate(m=>m._boardGetState().history.length),0);await sentence.hover();await sentence.getByRole('button',{name:'Apply',exact:true}).click();await sentence.getByRole('textbox',{name:'Expanded predicate',exact:true}).fill('slept peacefully on the warm rug');await sentence.hover();await sentence.getByRole('button',{name:'Apply',exact:true}).click();assert.equal(await sentence.evaluate(m=>m._boardGetState().history.length),3);
await sentence.getByRole('button',{name:'View previous sentences'}).click();assert(await sentence.locator('.sentence-history').isVisible());await sentence.locator('.sentence-history button').nth(1).click();assert.equal(await sentence.getByRole('textbox',{name:'Expanded predicate',exact:true}).textContent(),'slept on the warm rug');
await sentence.locator('input[type=file]').setInputFiles({name:'image.png',mimeType:'image/png',buffer:Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=80;const x=c.getContext('2d');x.fillStyle='#9abfa8';x.fillRect(0,0,80,80);return c.toDataURL().split(',')[1]}),'base64')});await page.waitForTimeout(300);assert(await sentence.locator('.sentence-image').isVisible());await sentence.locator('.sentence-drop').evaluate(el=>{const c=document.createElement('canvas');c.width=c.height=16;c.getContext('2d').fillRect(0,0,16,16);const bytes=Uint8Array.from(atob(c.toDataURL().split(',')[1]),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([bytes],'drop.png',{type:'image/png'}));el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}))});await page.waitForTimeout(300);assert(await sentence.locator('.sentence-image').isVisible());const state=await sentence.evaluate(m=>m._boardGetState());await page.evaluate(()=>TeacherTilesBoard.load(TeacherTilesBoard.capture()));assert.deepEqual(await sentence.evaluate(m=>m._boardGetState()),state);
await sentence.hover();const imageHeight=await sentence.locator('.sentence-drop').evaluate(el=>el.getBoundingClientRect().height);await sentence.getByRole('textbox',{name:'Expanded predicate',exact:true}).fill('walked through the park with the whole family '.repeat(20));assert(Math.abs(await sentence.locator('.sentence-drop').evaluate(el=>el.getBoundingClientRect().height)-imageHeight)<1);assert(imageHeight<=170);assert(await sentence.evaluate(el=>el.querySelector('.sentence-bottom').getBoundingClientRect().top-el.querySelector('.sentence-drop').getBoundingClientRect().bottom)<=13);assert(await sentence.locator('.sentence-draft').evaluate(el=>el.scrollHeight>el.clientHeight));await sentence.hover();await sentence.getByRole('button',{name:'Apply',exact:true}).click();assert(Math.abs(await sentence.locator('.sentence-drop').evaluate(el=>el.getBoundingClientRect().height)-imageHeight)<1);assert(imageHeight<=170);assert(await sentence.evaluate(el=>el.querySelector('.sentence-bottom').getBoundingClientRect().top-el.querySelector('.sentence-drop').getBoundingClientRect().bottom)<=13);
const sheet=page.locator('.spreadsheet-module');await sheet.hover();assert.equal(await sheet.locator('.sheet-format-toolbar .sheet-add-row').count(),1);assert.equal(await sheet.locator('.sheet-toolbar').count(),0);await sheet.locator('.sheet-add-row').click();assert.equal(await sheet.evaluate(m=>m._boardGetState().rows),13);assert.equal(await sheet.getByRole('button',{name:'Bold',exact:true}).evaluate(b=>getComputedStyle(b).borderRadius),'9px');
const noise=page.locator('.noise-modern');await noise.hover();await page.waitForTimeout(350);const on=await noise.evaluate(m=>m.querySelector('.nm-footer').getBoundingClientRect().bottom);await page.mouse.move(1450,950);await page.waitForTimeout(350);const off=await noise.evaluate(m=>m.querySelector('.nm-footer').getBoundingClientRect().bottom);assert(off>on+25);assert.equal(await noise.locator('.noise-start').evaluate(el=>getComputedStyle(el).visibility),'hidden');await noise.hover();await page.waitForTimeout(250);assert.equal(await noise.locator('.noise-start').evaluate(el=>getComputedStyle(el).visibility),'visible');await page.mouse.move(1450,950);
await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/sentence-expansion.png'});await sheet.hover();await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/spreadsheet-toolbar.png'});
const normalFont=await sentence.locator('.sentence-draft').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));await sentence.locator('.module-fullscreen').evaluate(el=>el.click());await page.waitForFunction(()=>!!document.fullscreenElement);await page.waitForTimeout(250);assert(await sentence.locator('.sentence-draft').evaluate(el=>parseFloat(getComputedStyle(el).fontSize))>normalFont*2);assert((await sentence.locator('.sentence-drop').boundingBox()).height<=180);await page.screenshot({path:'C:/Users/Jack/.codex/visualizations/2026/09/21/01a0c154-6a92-74e3-80e0-b301d930cec6/sentence-fullscreen.png'});await page.evaluate(()=>document.exitFullscreen());await page.waitForTimeout(250);assert.equal(await sentence.locator('.sentence-draft').evaluate(el=>parseFloat(getComputedStyle(el).fontSize)),normalFont);assert.deepEqual(errors,[]);console.log('Sentence editing/history/image/save restore, shared spreadsheet toolbar and Noise Meter hover layout passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
