function setupPrizeBoard(m){
  const importView=m.querySelector('.prizeboard-import'),dashboard=m.querySelector('.prizeboard-dashboard'),loaderAnchor=m.querySelector('.prizeboard-loader-anchor');
  const className=m.querySelector('.prizeboard-class-name'),classLogo=m.querySelector('.prizeboard-class-logo'),changeClass=m.querySelector('.prizeboard-change-class');
  const tabs=[...m.querySelectorAll('[data-prize-scope]')],grid=m.querySelector('.prizeboard-grid'),add=m.querySelector('.prizeboard-add');
  let activeClassId='',scope='student',prizes=[];const modal=makePrizeModal();
  const currentRoster=()=>readClassRosters().find(item=>item.id===activeClassId)||null;
  const statDefinition=id=>PRIZE_STAT_OPTIONS.find(item=>item.id===id)||PRIZE_STAT_OPTIONS[0];
  const notify=reason=>notifyBoardChanged(`prizeboard-${reason}`);
  const syncModuleSize=()=>requestAnimationFrame(()=>{
    if(!dashboard||dashboard.hidden)return;const count=Math.max(1,prizes.filter(p=>p.scope===scope).length);const width=Math.max(340,m.clientWidth-28);const cols=Math.max(1,Math.floor(width/190));const rows=Math.ceil(count/cols);const needed=245+rows*165;
    if(m.offsetHeight<needed)m.style.height=`${Math.min(BOARD_HEIGHT-m.offsetTop,needed)}px`;
  });
  const setClass=id=>{
    const roster=readClassRosters().find(item=>item.id===id);activeClassId=roster?.id||'';importView.hidden=Boolean(roster);dashboard.hidden=!roster;
    if(roster){className.textContent=roster.name;classLogo.textContent=normalizeClassLogo(roster.logo)}render();
  };
  const closeEditor=()=>modal.close();
  const openEditor=(existing=null)=>{
    const editing=existing?normalizePrize(existing):null;const working=editing||normalizePrize({scope,title:'',description:'',cost:1,image:prizePresetImage('gift')});
    modal.overlay.hidden=false;modal.panel.innerHTML=`<button class="prize-modal-close" type="button" aria-label="Close">×</button><div class="prize-editor"><div><small>${editing?'EDIT PRIZE':'NEW PRIZE'}</small><h2>${editing?'Update prize':'Create a prize'}</h2></div><label>Category<select class="prize-editor-scope"><option value="student">Prizes</option><option value="class">Whole Class Prizes</option></select></label><label>Title<input class="prize-editor-title" maxlength="80" placeholder="Prize title"></label><label>Description<textarea class="prize-editor-description" maxlength="400" rows="3" placeholder="What does the student earn?"></textarea></label><div class="prize-editor-row"><label>Cost<input class="prize-editor-cost" type="number" min="0" max="9999" step="1"></label><label>PBIS stat<select class="prize-editor-stat"></select></label></div><div><span class="prize-editor-label">Prize image</span><div class="prize-preset-grid"></div><label class="prize-upload">Upload your own<input type="file" accept="image/*"></label><div class="prize-editor-preview"><img alt="Prize preview"></div></div><div class="prize-editor-actions">${editing?'<button class="prize-editor-delete" type="button">Delete prize</button>':''}<button class="prize-editor-cancel" type="button">Cancel</button><button class="prize-editor-save" type="button">Save prize</button></div></div>`;
    const q=s=>modal.panel.querySelector(s),scopeSelect=q('.prize-editor-scope'),title=q('.prize-editor-title'),desc=q('.prize-editor-description'),cost=q('.prize-editor-cost'),stat=q('.prize-editor-stat'),preview=q('.prize-editor-preview img');
    scopeSelect.value=working.scope;title.value=working.title==='New Prize'?'':working.title;desc.value=working.description;cost.value=working.cost;preview.src=working.image;
    let selectedImage=working.image;
    const fillStats=()=>{const options=scopeSelect.value==='student'?PRIZE_STAT_OPTIONS.filter(item=>item.scope==='student'):PRIZE_STAT_OPTIONS.filter(item=>item.scope==='class');const wanted=stat.value||working.costStat;stat.replaceChildren(...options.map(item=>new Option(`${item.icon} ${item.label}`,item.id)));stat.value=options.some(item=>item.id===wanted)?wanted:options[0].id};fillStats();scopeSelect.addEventListener('change',fillStats);
    const presets=q('.prize-preset-grid');['gift','game','snack','choice','break','music','helper','mystery'].forEach(kind=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<img src="${prizePresetImage(kind)}" alt="${kind} preset">`;b.addEventListener('click',()=>{selectedImage=prizePresetImage(kind);preview.src=selectedImage});presets.append(b)});
    q('.prize-upload input').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{selectedImage=String(reader.result||selectedImage);preview.src=selectedImage};reader.readAsDataURL(file)});
    q('.prize-modal-close').addEventListener('click',closeEditor);q('.prize-editor-cancel').addEventListener('click',closeEditor);
    q('.prize-editor-delete')?.addEventListener('click',()=>{if(!confirm(`Delete ${working.title}?`))return;prizes=prizes.filter(item=>item.id!==working.id);closeEditor();render();notify('delete')});
    q('.prize-editor-save').addEventListener('click',()=>{const titleValue=title.value.trim();if(!titleValue){title.focus();return}const next=normalizePrize({id:editing?.id||prizeId(),scope:scopeSelect.value,title:titleValue,description:desc.value,cost:Number(cost.value),costStat:stat.value,image:selectedImage});if(editing)prizes=prizes.map(item=>item.id===editing.id?next:item);else prizes.push(next);scope=next.scope;closeEditor();render();notify('save')});
  };
  const openPrize=(prize)=>{
    const roster=currentRoster();if(!roster)return;const stat=statDefinition(prize.costStat);modal.overlay.hidden=false;
    const students=roster.students;modal.panel.innerHTML=`<button class="prize-modal-close" type="button" aria-label="Close">×</button><div class="prize-detail"><img class="prize-detail-image" src="${prize.image}" alt=""><div class="prize-detail-copy"><small>${prize.scope==='class'?'WHOLE CLASS PRIZE':'STUDENT PRIZE'}</small><h2></h2><p></p><div class="prize-detail-cost"><span>${stat.icon}</span><strong>${prize.cost}</strong><small>${stat.label}</small></div><div class="prize-redeem-target"></div><div class="prize-detail-balance"></div><div class="prize-detail-actions"><button class="prize-edit" type="button">Edit</button><button class="prize-redeem" type="button">Redeem prize</button></div></div></div>`;
    modal.panel.querySelector('h2').textContent=prize.title;modal.panel.querySelector('.prize-detail-copy>p').textContent=prize.description||'No description added.';
    const targetWrap=modal.panel.querySelector('.prize-redeem-target'),balance=modal.panel.querySelector('.prize-detail-balance'),redeem=modal.panel.querySelector('.prize-redeem');let student='';
    if(prize.scope==='student'){
      const label=document.createElement('label');label.innerHTML='<span>Redeem for</span>';const select=document.createElement('select');select.append(new Option(students.length?'Choose a student…':'No students in this class',''));students.forEach(name=>select.add(new Option(name,name)));label.append(select);targetWrap.append(label);select.addEventListener('change',()=>{student=select.value;refreshBalance()});
    }else{targetWrap.innerHTML=`<div class="prize-class-target"><span aria-hidden="true">${normalizeClassLogo(roster.logo)}</span><strong>${roster.name}</strong><small>Whole class redemption</small></div>`}
    const refreshBalance=()=>{const targetStudent=stat.scope==='student'?student:'';const amount=pbisBalance(currentRoster(),prize.costStat,targetStudent);const missing=amount<prize.cost;balance.innerHTML=`<span>Available balance</span><strong>${amount} ${stat.label}</strong>${missing?'<small>Not enough credit for this reward.</small>':''}`;redeem.disabled=missing||(prize.scope==='student'&&!student)};refreshBalance();
    modal.panel.querySelector('.prize-modal-close').addEventListener('click',()=>modal.close());modal.panel.querySelector('.prize-edit').addEventListener('click',()=>openEditor(prize));
    redeem.addEventListener('click',async()=>{const recipient=prize.scope==='class'?roster.name:student;if(!recipient)return;const spendStudent=stat.scope==='student'?student:'';if(pbisBalance(currentRoster(),prize.costStat,spendStudent)<prize.cost){refreshBalance();return}adjustPbisBalance(activeClassId,prize.costStat,-prize.cost,{studentName:spendStudent});modal.panel.innerHTML=`<button class="prize-modal-close" type="button" aria-label="Close">×</button><div class="prize-redeemed"><span aria-hidden="true">🎉</span><small>PRIZE REDEEMED</small><h2>${prize.title}</h2><p><strong>${recipient}</strong> redeemed this prize for ${prize.cost} ${stat.label}.</p><div class="prize-redeemed-actions"><button class="prize-coupon" type="button">Download coupon PNG</button><button class="prize-done" type="button">Done</button></div></div>`;modal.panel.querySelector('.prize-modal-close').addEventListener('click',()=>modal.close());modal.panel.querySelector('.prize-done').addEventListener('click',()=>modal.close());modal.panel.querySelector('.prize-coupon').addEventListener('click',()=>downloadPrizeCoupon(prize,roster,recipient,stat.label));});
  };
  const render=()=>{
    tabs.forEach(tab=>{const on=tab.dataset.prizeScope===scope;tab.classList.toggle('is-active',on);tab.setAttribute('aria-selected',String(on))});grid.replaceChildren();
    const visible=prizes.filter(item=>item.scope===scope);if(!visible.length){const empty=document.createElement('button');empty.type='button';empty.className='prizeboard-empty';empty.innerHTML=`<span aria-hidden="true">${scope==='class'?'🎉':'🎁'}</span><strong>No ${scope==='class'?'whole-class prizes':'prizes'} yet</strong><small>Add your first reward to this board.</small>`;empty.addEventListener('click',()=>openEditor());grid.append(empty)}
    visible.forEach(prize=>{const stat=statDefinition(prize.costStat);const card=document.createElement('article');card.className='prize-card';card.innerHTML=`<button class="prize-card-open" type="button"><img alt=""><span class="prize-card-copy"><strong></strong><small></small></span><span class="prize-card-cost"><i>${stat.icon}</i><b>${prize.cost}</b></span></button><button class="prize-card-delete" type="button" title="Delete prize">×</button>`;const openButton=card.querySelector('.prize-card-open'),deleteButton=card.querySelector('.prize-card-delete');openButton.setAttribute('aria-label',`Open ${prize.title}`);deleteButton.setAttribute('aria-label',`Delete ${prize.title}`);card.querySelector('img').src=prize.image;card.querySelector('.prize-card-copy strong').textContent=prize.title;card.querySelector('.prize-card-copy small').textContent=prize.description||stat.label;openButton.addEventListener('click',()=>openPrize(prize));deleteButton.addEventListener('click',event=>{event.stopPropagation();if(!confirm(`Delete ${prize.title}?`))return;prizes=prizes.filter(item=>item.id!==prize.id);render();notify('delete')});grid.append(card)});syncModuleSize();
  };
  tabs.forEach(tab=>tab.addEventListener('click',()=>{scope=tab.dataset.prizeScope;render();notify('tab')}));add.addEventListener('click',()=>openEditor());changeClass.addEventListener('click',()=>{activeClassId='';importView.hidden=false;dashboard.hidden=true;render();notify('class')});
  const detach=attachClassRosterLoader(loaderAnchor,(_,roster)=>{setClass(roster.id);notify('class')});
  m.querySelector('.prizeboard-bg').addEventListener('click',()=>cycleData(m,'bg',['white','cream','blue','pink','green','lavender','charcoal']));m.querySelector('.prizeboard-font').addEventListener('click',()=>cycleData(m,'font',FONT_OPTIONS));m.querySelector('.prizeboard-text-color').addEventListener('click',()=>cycleData(m,'text',['dark','soft','blue','rose','white','cream']));
  const ro=new ResizeObserver(syncModuleSize);ro.observe(m);
  const refresh=()=>{if(activeClassId&&!currentRoster())setClass('');else render()};window.addEventListener('teachertiles:classeschange',refresh);window.addEventListener('teachertiles:starchartchange',refresh);window.addEventListener('teachertiles:classmeterchange',refresh);window.addEventListener('teachertiles:collectionchange',refresh);window.addEventListener('teachertiles:punchcardchange',refresh);window.addEventListener('teachertiles:racerchange',refresh);
  m._boardGetState=()=>({activeClassId,scope,prizes:prizes.map(normalizePrize)});m._boardSetState=state=>{if(!state)return;scope=state.scope==='class'?'class':'student';prizes=Array.isArray(state.prizes)?state.prizes.map(normalizePrize):[];setClass(String(state.activeClassId||''));render()};
  const prior=m._cleanup;m._cleanup=()=>{prior?.();detach();ro.disconnect();modal.overlay.remove();window.removeEventListener('teachertiles:classeschange',refresh);window.removeEventListener('teachertiles:starchartchange',refresh);window.removeEventListener('teachertiles:classmeterchange',refresh);window.removeEventListener('teachertiles:collectionchange',refresh);window.removeEventListener('teachertiles:punchcardchange',refresh);window.removeEventListener('teachertiles:racerchange',refresh)};
  render();
}
